# 5 — Split-cell-line reactome terms (quick check)

Per-cell-line **split** version of the enrichment analysis from notebook 3.
Instead of pooling the "small / close-enhancer + up-regulated" gene sets from
both cell lines of a comparison, here each **ordered** cell-line pair is run on
its own so we can see what each side produces in isolation.

We run **12 experiments** = 6 ordered cell-line pairs × 2 jump definitions:

* **with mids** — `small → mid` **and** `small → large` (i.e. *cell1 small vs cell2 mid/large*)
* **without mids** — `small → large` only (i.e. *cell1 small vs cell2 large*)

For every experiment we take only the **cell1** gene set (up-regulated in cell1
*and* close/small in cell1, having jumped to mid/large in cell2), enrich against
**Reactome_Pathways_2024**, and print the terms as **text** (no figure yet).

In [1]:
import os.path

import pyranges

gencode = pyranges.read_gtf("../../data/gencode.v40.basic.annotation.gtf")

genes_from_gencode = (
    gencode
    [(gencode['Feature'] == 'gene')]
    [['Chromosome', 'Start', 'End', 'gene_id']]
)

genes_from_gencode['gene_id'] = genes_from_gencode['gene_id'].str.split('.').str[0]

genes_from_gencode

index    |    Chromosome    Start    End      gene_id
int64    |    object        int64    int64    object
-------  ---  ------------  -------  -------  ---------------
0        |    chr1          11868    14409    ENSG00000223972
12       |    chr1          14403    29570    ENSG00000227232
25       |    chr1          17368    17436    ENSG00000278267
28       |    chr1          29553    31109    ENSG00000243485
...      |    ...           ...      ...      ...
1926902  |    chrM          14673    14742    ENSG00000210194
1926905  |    chrM          14746    15887    ENSG00000198727
1926910  |    chrM          15887    15953    ENSG00000210195
1926913  |    chrM          15955    16023    ENSG00000210196
PyRanges with 61544 rows, 4 columns, and 1 index columns.
Contains 25 chromosomes.

In [2]:
import pandas as pd
from pydeseq2.dds import DeseqDataSet
from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats

with open("../../data/rnaseq/gm12878_read_count.txt", "r") as f:
    f.readline()
    gm12878_counts_df = pd.read_csv(f, index_col=0, sep="\t")


with open("../../data/rnaseq/h1esc_read_count.txt", "r") as f:
    f.readline()
    h1esc_counts_df = pd.read_csv(f, index_col=0, sep="\t")

with open("../../data/rnaseq/hffc6_read_count.txt", "r") as f:
    f.readline()
    hffc6_counts_df = pd.read_csv(f, index_col=0, sep="\t")

gm12878_counts_df = gm12878_counts_df[['ENCFF800HIP.filtered.bam', 'ENCFF991KKX.filtered.bam']].T
h1esc_counts_df = h1esc_counts_df[['ENCFF675NTU.filtered.bam', 'ENCFF379NOY.filtered.bam']].T
hffc6_counts_df = hffc6_counts_df[['ENCFF307KUI.filtered.bam', 'ENCFF294BSI.filtered.bam', 'ENCFF937TEI.filtered.bam']].T

def compute_deseq_stats_for_2_celllines(cellline1_counts_df, cellline2_counts_df, cellline1_name="CellLine1", cellline2_name="CellLine2"):
    cl1_vs_cl2_counts_df = pd.concat(
        [cellline1_counts_df, cellline2_counts_df]
    )

    cl1_vs_cl2_metadata_df = pd.DataFrame(
        {
            "condition": [cellline1_name] * cellline1_counts_df.shape[0] + [cellline2_name] * cellline2_counts_df.shape[0]
        },
        index=cl1_vs_cl2_counts_df.index,
    )

    inference = DefaultInference(n_cpus=8)
    dds = DeseqDataSet(
        counts=cl1_vs_cl2_counts_df,
        metadata=cl1_vs_cl2_metadata_df,
        design="~condition",
        refit_cooks=True,
        inference=inference,
    )

    dds.deseq2()
    stats = DeseqStats(dds, contrast=["condition", cellline2_name, cellline1_name])
    stats.summary()

    stats.lfc_shrink(coeff=f"condition[T.{cellline2_name}]")

    results_df = stats.results_df.dropna()
    results_df['symbol'] = results_df.index
    return results_df

if os.path.exists("../../data/deseq/gm12878_vs_h1esc_results.parquet"):
    gm12878_vs_h1esc_results_df = pd.read_parquet("../../data/deseq/gm12878_vs_h1esc_results.parquet")
else:
    gm12878_vs_h1esc_results_df = compute_deseq_stats_for_2_celllines(
        gm12878_counts_df,
        h1esc_counts_df,
        cellline1_name="GM12878",
        cellline2_name="H1ESC"
    )
    gm12878_vs_h1esc_results_df.to_parquet("../../data/deseq/gm12878_vs_h1esc_results.parquet")

if os.path.exists("../../data/deseq/h1esc_vs_hffc6_results.parquet"):
    h1esc_vs_hffc6_results_df = pd.read_parquet("../../data/deseq/h1esc_vs_hffc6_results.parquet")
else:
    h1esc_vs_hffc6_results_df = compute_deseq_stats_for_2_celllines(
        h1esc_counts_df,
        hffc6_counts_df,
        cellline1_name="H1ESC",
        cellline2_name="HFFC6"
    )
    h1esc_vs_hffc6_results_df.to_parquet("../../data/deseq/h1esc_vs_hffc6_results.parquet")

if os.path.exists("../../data/deseq/gm12878_vs_hffc6_results.parquet"):
    gm12878_vs_hffc6_results_df = pd.read_parquet("../../data/deseq/gm12878_vs_hffc6_results.parquet")
else:
    gm12878_vs_hffc6_results_df = compute_deseq_stats_for_2_celllines(
        gm12878_counts_df,
        hffc6_counts_df,
        cellline1_name="GM12878",
        cellline2_name="HFFC6",
    )
    gm12878_vs_hffc6_results_df.to_parquet("../../data/deseq/gm12878_vs_hffc6_results.parquet")

In [3]:
# get_comparison_table_2_cell_lines expects a DESeq frame oriented so that
# log2FoldChange > 0  <=>  up-regulated in cell2 (the second name passed).
# We have GM_vs_H1, GM_vs_HFFC6 and H1_vs_HFFC6; build the three reverse
# orientations by flipping the sign of the log2 fold-change.
def reverse_contrast(df):
    reversed_df = df.copy()
    reversed_df['log2FoldChange'] = -reversed_df['log2FoldChange']
    return reversed_df

h1esc_vs_gm12878_results_df = reverse_contrast(gm12878_vs_h1esc_results_df)
hffc6_vs_gm12878_results_df = reverse_contrast(gm12878_vs_hffc6_results_df)
hffc6_vs_h1esc_results_df   = reverse_contrast(h1esc_vs_hffc6_results_df)

In [4]:
gene_to_closest_avg_enhancer_all = pd.read_parquet("../../data/whole_chromosomes/genes_all_cell_lines_v3.snappy.parquet")
gm12878_gene_to_closest_avg_enhancer_all = gene_to_closest_avg_enhancer_all[gene_to_closest_avg_enhancer_all['cell_line'] == 'GM12878'].set_index('gene_id').drop(columns=['cell_line'])
h1esc_gene_to_closest_avg_enhancer_all = gene_to_closest_avg_enhancer_all[gene_to_closest_avg_enhancer_all['cell_line'] == 'H1ESC'].set_index('gene_id').drop(columns=['cell_line'])
hffc6_gene_to_closest_avg_enhancer_all = gene_to_closest_avg_enhancer_all[gene_to_closest_avg_enhancer_all['cell_line'] == 'HFFC6'].set_index('gene_id').drop(columns=['cell_line'])

def add_chromosome_and_quartiles(df, name):
    df = df.merge(genes_from_gencode[['gene_id', 'Chromosome']], left_index=True, right_on='gene_id', how='left').set_index('gene_id')

    def compute_quartiles(group):
        q1 = group['min_dist'].quantile(0.33)
        q3 = group['min_dist'].quantile(0.67)
        def label_quartile(x):
            if x <= q1:
                return 'small'
            elif x <= q3:
                return 'mid'
            else:
                return 'large'
        group['quartile_cat'] = group['min_dist'].apply(label_quartile)
        return group

    df = df.groupby('Chromosome', group_keys=False).apply(compute_quartiles, include_groups=False)
    return df

gm12878_gene_to_closest_avg_enhancer_all = add_chromosome_and_quartiles(gm12878_gene_to_closest_avg_enhancer_all, 'gm12878')
hffc6_gene_to_closest_avg_enhancer_all = add_chromosome_and_quartiles(hffc6_gene_to_closest_avg_enhancer_all, 'hffc6')
h1esc_gene_to_closest_avg_enhancer_all = add_chromosome_and_quartiles(h1esc_gene_to_closest_avg_enhancer_all, 'h1esc')

In [5]:
import numpy as np
from gprofiler import GProfiler

gp = GProfiler(
    user_agent='enhancer3d',
    return_dataframe=True,
)

def get_comparison_table_2_cell_lines(
    cell1_distances_df,
    cell2_distances_df,
    deseq_results_df,
    cell1_name,
    cell2_name,
    log2fc_threshold=2,
    padj_threshold=0.05,
    enable_jump_filtering=True,
    enable_expression_filtering=True,
    cell1_jump_categories=(
        "Increased (small to large)",
        "Increased (small to mid)",
    ),
    cell2_jump_categories=(
        "Decreased (large to small)",
        "Decreased (mid to small)",
    )
):
    cell1_jump_categories = list(cell1_jump_categories)
    cell2_jump_categories = list(cell2_jump_categories)

    deseq_results_df = deseq_results_df.copy()
    deseq_results_df.index = deseq_results_df.index.str.split('.').str[0]

    deseq_results_df = deseq_results_df[
        (deseq_results_df["padj"] < padj_threshold)
        & (deseq_results_df["log2FoldChange"].abs() > log2fc_threshold)
    ]

    cell1_distances_df = cell1_distances_df.copy()
    cell1_distances_df['norm_min_dist'] = (
        (cell1_distances_df['min_dist'] - cell1_distances_df['min_dist'].min()) / (cell1_distances_df['min_dist'].max() - cell1_distances_df['min_dist'].min())
    )

    cell2_distances_df = cell2_distances_df.copy()
    cell2_distances_df['norm_min_dist'] = (
        (cell2_distances_df['min_dist'] - cell2_distances_df['min_dist'].min()) / (cell2_distances_df['min_dist'].max() - cell2_distances_df['min_dist'].min())
    )

    combined_df = cell1_distances_df.merge(
        cell2_distances_df,
        left_index=True,
        right_index=True,
        how="inner",
        suffixes=(f"_{cell1_name}", f"_{cell2_name}")
    )

    combined_df["log_dist_ratio"] = np.log2(combined_df[f"min_dist_{cell1_name}"] / combined_df[f"min_dist_{cell2_name}"])
    combined_df["dist_diff"] = combined_df[f"min_dist_{cell1_name}"] - combined_df[f"min_dist_{cell2_name}"]

    combined_df["norm_dist_diff"] = combined_df[f"norm_min_dist_{cell1_name}"] - combined_df[f"norm_min_dist_{cell2_name}"]
    combined_df["log_norm_dist_ratio"] = np.log2(combined_df[f"norm_min_dist_{cell1_name}"] / combined_df[f"norm_min_dist_{cell2_name}"])

    def get_quartile_change(row):
        q1 = row[f"quartile_cat_{cell1_name}"]
        q2 = row[f"quartile_cat_{cell2_name}"]

        if q1 == q2:
            return "No change"

        categories = ["small", "mid", "large"]
        idx1 = categories.index(q1)
        idx2 = categories.index(q2)

        if idx1 > idx2:
            return f"Decreased ({q1} to {q2})"
        else:
            return f"Increased ({q1} to {q2})"

    combined_df["quartile_change"] = combined_df.apply(get_quartile_change, axis=1)

    merged_df = combined_df.merge(
        deseq_results_df[["log2FoldChange", "padj"]],
        left_index=True,
        right_index=True,
        how="inner"
    )

    merged_df_for_genes = merged_df.copy()

    if enable_jump_filtering and enable_expression_filtering:
        cell_line_1_upregulated_jumper_genes = merged_df_for_genes[
            (merged_df_for_genes["log2FoldChange"] < -log2fc_threshold)
            & (merged_df_for_genes["quartile_change"].isin(cell1_jump_categories))
        ]
    elif enable_jump_filtering:
        cell_line_1_upregulated_jumper_genes = merged_df_for_genes[
            (merged_df_for_genes["quartile_change"].isin(cell1_jump_categories))
        ]
    elif enable_expression_filtering:
        cell_line_1_upregulated_jumper_genes = merged_df_for_genes[
            (merged_df_for_genes["log2FoldChange"] < -log2fc_threshold)
        ]

    if enable_jump_filtering and enable_expression_filtering:
        cell_line_2_upregulated_jumper_genes = merged_df_for_genes[
            (merged_df_for_genes["log2FoldChange"] > log2fc_threshold)
            & (merged_df_for_genes["quartile_change"].isin(cell2_jump_categories))
        ]
    elif enable_jump_filtering:
        cell_line_2_upregulated_jumper_genes = merged_df_for_genes[
            (merged_df_for_genes["quartile_change"].isin(cell2_jump_categories))
        ]
    elif enable_expression_filtering:
         cell_line_2_upregulated_jumper_genes = merged_df_for_genes[
            (merged_df_for_genes["log2FoldChange"] > log2fc_threshold)
        ]

    return cell_line_1_upregulated_jumper_genes, cell_line_2_upregulated_jumper_genes

In [6]:
import gseapy

def get_enrichment_results(gene_list, gene_sets):
    columns = ['Term', 'P-value', 'Adjusted P-value', 'Overlap', 'Combined Score', 'Genes']

    enr = gseapy.enrichr(
        gene_list=gene_list,
        gene_sets=gene_sets,
        organism='Human',
        outdir=None,
        cutoff=0.05
    )

    # Enrichr can return an empty frame (no terms / API hiccup); keep the schema stable.
    if enr.results is None or enr.results.empty:
        return pd.DataFrame(columns=columns + ['Genes Ratio', 'Genes Number'])

    results = enr.results[columns].copy()
    results['Genes Ratio'] = results['Genes'].apply(lambda x: len(x.split(';')) / len(gene_list))
    results['Genes Number'] = results['Genes'].apply(lambda x: len(x.split(';')))
    return results.reset_index(drop=True)

In [7]:
def get_cell1_small_gene_names(cell1_distances_df, cell2_distances_df, deseq_results_df,
                               cell1_name, cell2_name, include_mid=True):
    """Genes up-regulated in cell1 that are SMALL (close enhancer) in cell1 and
    jumped to mid/large in cell2. With include_mid=False, only small->large counts."""
    cell1_jump_categories = ["Increased (small to large)"]
    if include_mid:
        cell1_jump_categories.append("Increased (small to mid)")

    cell1_genes_df, _ = get_comparison_table_2_cell_lines(
        cell1_distances_df,
        cell2_distances_df,
        deseq_results_df,
        cell1_name,
        cell2_name,
        cell1_jump_categories=tuple(cell1_jump_categories),
    )

    if cell1_genes_df.empty:
        return []

    names = (
        gp.convert(organism='hsapiens', query=cell1_genes_df.index.tolist())
        [['converted', 'name']]
        .set_index('converted', drop=True)
    )
    return list(filter(None, names['name'].tolist()))


distance_dfs = {
    "GM12878": gm12878_gene_to_closest_avg_enhancer_all,
    "H1ESC":   h1esc_gene_to_closest_avg_enhancer_all,
    "HFFC6":   hffc6_gene_to_closest_avg_enhancer_all,
}

# 6 ordered (cell1, cell2) pairs -> the contrast oriented so log2FC>0 == up in cell2.
experiments = [
    ("GM12878", "H1ESC",   gm12878_vs_h1esc_results_df),
    ("GM12878", "HFFC6",   gm12878_vs_hffc6_results_df),
    ("H1ESC",   "GM12878", h1esc_vs_gm12878_results_df),
    ("H1ESC",   "HFFC6",   h1esc_vs_hffc6_results_df),
    ("HFFC6",   "GM12878", hffc6_vs_gm12878_results_df),
    ("HFFC6",   "H1ESC",   hffc6_vs_h1esc_results_df),
]


def run_split_experiments(include_mid):
    target = "mid/large" if include_mid else "large"
    results = {}
    for cell1, cell2, deseq_df in experiments:
        label = f"{cell1} small vs {cell2} {target}"
        gene_names = get_cell1_small_gene_names(
            distance_dfs[cell1], distance_dfs[cell2], deseq_df,
            cell1, cell2, include_mid=include_mid,
        )
        reactomes = get_enrichment_results(gene_names, gene_sets='Reactome_Pathways_2024')
        results[label] = (gene_names, reactomes)

        print("=" * 90)
        print(f"{label}   ({len(gene_names)} genes, {len(reactomes)} reactome terms)")
        print("=" * 90)
        for term in reactomes['Term']:
            print(f"  {term}")
        print()
    return results

## Set A — *with mids* (cell1 small vs cell2 **mid/large**)

`small → mid` and `small → large` jumps.

In [8]:
results_with_mid = run_split_experiments(include_mid=True)

==========================================================================================
GM12878 small vs H1ESC mid/large   (242 genes, 602 reactome terms)
==========================================================================================
  Cytokine Signaling in Immune System
  Immune System
  Signaling by Interleukins
  Interleukin-3, Interleukin-5 and GM-CSF Signaling
  GPVI-mediated Activation Cascade
  Innate Immune System
  Regulation of Signaling by CBL
  Interleukin-2 Family Signaling
  Toll-like Receptor Cascades
  Toll Like Receptor 4 (TLR4) Cascade
  Signaling by CSF1 (M-CSF) in Myeloid Cells
  Signaling by the B Cell Receptor (BCR)
  Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers
  Interferon Gamma Signaling
  Adaptive Immune System
  TAK1-dependent IKK and NF-kappa-B Activation
  Interleukin-4 and Interleukin-13 Signaling
  RUNX3 Regulates Immune Response and Cell Migration
  FLT3 Signaling Through SRC Family Kinases
  Toxicity of Botulinum Toxin Type D (botD)
  Toxicity of Botulinum Toxin Type F (botF)
  Regulation of IFNA IFNB Signaling
  Signaling by Erythropoietin
  Interleukin-7 Signaling
  Platelet Activation, Signaling and Aggregation
  TNFR2 Non-Canonical NF-kB Pathway
  Interleukin Receptor SHC Signaling
  TRP Channels
  DAP12 Signaling
  TNFs Bind Their Physiological Receptors
  Toxicity of Botulinum Toxin Type A (botA)
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  Interleukin-1 Family Signaling
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  MyD88 Dependent Cascade Initiated on Endosome
  Toll Like Receptor 3 (TLR3) Cascade
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Neutrophil Degranulation
  Caspase-mediated Cleavage of Cytoskeletal Proteins
  Erythropoietin Activates Phosphoinositide-3-kinase (PI3K)
  Interleukin-2 Signaling
  MyD88-independent TLR4 Cascade
  TRIF (TICAM1)-mediated TLR4 Signaling
  Toll Like Receptor 9 (TLR9) Cascade
  FLT3 Signaling
  TCR Signaling
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  Potential Therapeutics for SARS
  RUNX3 Regulates NOTCH Signaling
  Interleukin-15 Signaling
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Generation of Second Messenger Molecules
  Costimulation by the CD28 Family
  Interferon Alpha Beta Signaling
  Regulation of MITF-M-dependent Genes Involved in Pigmentation
  Fcgamma Receptor (FCGR) Dependent Phagocytosis
  Signaling by SCF-KIT
  Interferon Signaling
  Regulation of Gene Expression in Late Stage (Branching Morphogenesis) Pancreatic Bud Precursor Cells
  STING Mediated Induction of Host Immune Responses
  DAP12 Interactions
  Platelet Sensitization by LDL
  Purine Catabolism
  TNF Receptor Superfamily (TNFSF) Members Mediating Non-Canonical NF-kB Pathway
  C-type Lectin Receptors (CLRs)
  CLEC7A (Dectin-1) Signaling
  G Alpha (Z) Signalling Events
  Regulation of NF-kappa B Signaling
  MITF-M-regulated Melanocyte Development
  Parasitic Infection Pathways
  Leishmania Infection
  TP53 Regulates Transcription of Genes Involved in Cytochrome C Release
  Synthesis of PIPs at the Plasma Membrane
  Neurotoxicity of Clostridium Toxins
  CD209 (DC-SIGN) Signaling
  Transcriptional Regulation by RUNX1
  Interleukin-1 Signaling
  G Beta Gamma Signalling Through PI3Kgamma
  Glycogen Metabolism
  Inactivation of CSF3 (G-CSF) Signaling
  TRAF6 Mediated NF-kB Activation
  Signal Transduction
  Cytosolic Sensors of Pathogen-Associated DNA
  Synthesis of Substrates in N-glycan Biosythesis
  FCERI Mediated Ca+2 Mobilization
  Cell Recruitment (Pro-Inflammatory Response)
  Purinergic Signaling in Leishmaniasis Infection
  Effects of PIP2 Hydrolysis
  Integrin Signaling
  FOXO-mediated Transcription
  Phosphorylation of CD3 and TCR Zeta Chains
  PD-1 Signaling
  Dectin-2 Family
  Signaling by ALK
  Signaling by CSF3 (G-CSF)
  FCGR3A-mediated IL10 Synthesis
  Antigen Presentation Folding, Assembly and Peptide Loading of Class I MHC
  G-protein Beta Gamma Signalling
  GPCR Downstream Signalling
  Sialic Acid Metabolism
  Signaling by GPCR
  NGF-independant TRKA Activation
  NTRK2 Activates RAC1
  Biosynthesis of E-series 18(S)-resolvins
  RUNX3 Regulates BCL2L11 (BIM) Transcription
  Drug-mediated Inhibition of CDK4 CDK6 Activity
  The Fatty Acid Cycling Model
  Toxicity of Botulinum Toxin Type E (botE)
  MECP2 Regulates Transcription Factors
  Nuclear Events Stimulated by ALK Signaling in Cancer
  Nucleotide Catabolism
  CD28 Co-Stimulation
  Biosynthesis of the N-glycan Precursor (Dolichol LLO) and Transfer to a Nascent Protein
  Activated NTRK2 Signals Through CDK5
  Activation of TRKA Receptors
  Biosynthesis of EPA-derived SPMs
  Biosynthesis of Lipoxins (LX)
  CLEC7A Inflammasome Pathway
  RUNX1 Regulates Transcription of Genes Involved in BCR Signaling
  Scavenging by Class B Receptors
  GDP-fucose Biosynthesis
  Constitutive Signaling by Aberrant PI3K in Cancer
  Apoptotic Cleavage of Cellular Proteins
  PI Metabolism
  Fc Epsilon Receptor (FCERI) Signaling
  Platelet Aggregation (Plug Formation)
  DDX58 IFIH1-mediated Induction of Interferon-Alpha Beta
  Transcriptional Regulation by RUNX3
  Platelet Homeostasis
  Parasite Infection
  FCGR3A-mediated Phagocytosis
  Leishmania Phagocytosis
  Programmed Cell Death
  Activated NTRK2 Signals Through FYN
  Activated NTRK2 Signals Through PI3K
  Phosphate Bond Hydrolysis by NUDT Proteins
  DEx H-box Helicases Activate Type I IFN and Inflammatory Cytokines Production
  RUNX3 Regulates CDKN1A Transcription
  Release of Apoptotic Factors From the Mitochondria
  Erythropoietin Activates Phospholipase C Gamma (PLCG)
  IkBA Variant Leads to EDA-ID
  Mitochondrial Uncoupling
  RET Signaling
  Regulation of Beta-Cell Development
  mRNA Editing C to U Conversion
  Binding of TCF LEF CTNNB1 to Target Gene Promoters
  Biosynthesis of Maresins
  RUNX3 Regulates WNT Signaling
  RUNX3 Regulates YAP1-mediated Transcription
  Regulation of NFE2L2 Gene Expression
  Regulation of Gene Expression in Early Pancreatic Precursor Cells
  Formation of the Editosome
  Interleukin-18 Signaling
  TP53 Regulates Transcription of Cell Death Genes
  Intra-Golgi Traffic
  Uptake and Actions of Bacterial Toxins
  Phospholipid Metabolism
  FCGR Activation
  MITF-M-dependent Gene Expression
  Interleukin-10 Signaling
  Mitochondrial Protein Degradation
  Activated NTRK2 Signals Through RAS
  Activation of PUMA and Translocation to Mitochondria
  Nef and Signal Transduction
  Atorvastatin ADME
  PTK6 Regulates RTKs and Their Effectors AKT1 and DOK1
  Formyl Peptide Receptors Bind Formyl Peptides and Many Other Ligands
  Synthesis of 5-Eicosatetraenoic Acids
  Interleukin-1 Processing
  Interleukin-9 Signaling
  Microbial Modulation of RIPK1-mediated Regulated Necrosis
  P75 NTR Receptor-Mediated Signalling
  Heme Signaling
  Hemostasis
  RNA Polymerase I Transcription Initiation
  Anti-inflammatory Response Favouring Leishmania Parasite Infection
  Leishmania Parasite Growth and Survival
  mRNA Editing
  Activation of Ca-permeable Kainate Receptor
  RUNX3 Regulates p14-ARF
  Regulation of FOXO Transcriptional Activity by Acetylation
  Glucocorticoid Biosynthesis
  Interleukin-21 Signaling
  Tetrahydrobiopterin (BH4) Synthesis, Recycling, Salvage and Regulation
  Ionotropic Activity of Kainate Receptors
  Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity
  Apoptotic Execution Phase
  Activated NTRK2 Signals Through FRS2 and FRS3
  Androgen Biosynthesis
  RHO GTPases Activate KTN1
  Regulated Proteolysis of p75NTR
  Transport of Organic Anions
  Role of Phospholipids in Phagocytosis
  Stimuli-sensing Channels
  Apoptosis
  Activation of NF-kappaB in B Cells
  Adipogenesis
  PI3K AKT Signaling in Cancer
  Intrinsic Pathway for Apoptosis
  NOTCH2 Intracellular Domain Regulates Transcription
  PECAM1 Interactions
  Peptide Hormone Biosynthesis
  Pyrimidine Catabolism
  Defective RIPK1-mediated Regulated Necrosis
  Endosomal Vacuolar Pathway
  TP53 Regulates Transcription of Caspase Activators and Caspases
  TP53 Regulates Transcription of Death Receptors and Ligands
  PI5P, PP2A and IER3 Regulate PI3K AKT Signaling
  FCERI Mediated MAPK Activation
  Transcriptional Activation of Mitochondrial Biogenesis
  Neurexins and Neuroligins
  NF-kB Is Activated and Signals Survival
  Nephron Development
  Advanced Glycosylation Endproduct Receptor Signaling
  IRF3-mediated Induction of Type I IFN
  The Activation of Arylsulfatases
  NRAGE Signals Death Through JNK
  Signaling by Receptor Tyrosine Kinases
  Negative Regulation of the PI3K AKT Network
  Physiological Factors
  Regulation of IFNG Signaling
  Regulation of TP53 Activity Through Association With Co-factors
  Glycogen Breakdown (Glycogenolysis)
  Glycogen Synthesis
  TP53 Regulates Transcription of Cell Death Genes With Uncertain Role in P53-Dependent Apoptosis
  Tryptophan Catabolism
  Regulated Necrosis
  Ion Channel Transport
  YAP1- and WWTR1 (TAZ)-stimulated Gene Expression
  p130Cas Linkage to MAPK Signaling for Integrins
  GRB2 SOS Provides Linkage to MAPK Signaling for Integrins
  Transcriptional Regulation by MECP2
  MAP Kinase Activation
  Rab Regulation of Trafficking
  p75NTR Signals via NF-kB
  Regulation of KIT Signaling
  Elevation of Cytosolic Ca2+ Levels
  Signal Regulatory Protein Family Interactions
  Glycogen Storage Diseases
  Heme Degradation
  MAP3K8 (TPL2)-dependent MAPK1 3 Activation
  Regulation of Endogenous Retroelements by Piwi-interacting RNAs (piRNAs)
  Membrane Trafficking
  Aberrant Regulation of Mitotic G1 S Transition in Cancer Due to RB1 Defects
  Biosynthesis of DHA-derived SPMs
  RIP-mediated NFkB Activation via ZBP1
  Defective Binding of RB1 Mutants to E2F1,(E2F2, E2F3)
  FOXO-mediated Transcription of Cell Cycle Genes
  GAB1 Signalosome
  The NLRP3 Inflammasome
  Downstream Signaling Events of B Cell Receptor (BCR)
  Mitochondrial Unfolded Protein Response (UPRmt)
  ABC Transporters in Lipid Homeostasis
  Activation of SMO
  Pre-NOTCH Processing in Golgi
  Prevention of Phagosomal-Lysosomal Fusion
  Synthesis of Glycosylphosphatidylinositol (GPI)
  Lewis Blood Group Biosynthesis
  MECP2 Regulates Neuronal Receptors and Channels
  Circadian Clock
  Interleukin-17 Signaling
  SARS-CoV Infections
  Biosynthesis of Specialized Proresolving Mediators (SPMs)
  Intra-Golgi and Retrograde Golgi-to-ER Traffic
  NOTCH4 Intracellular Domain Regulates Transcription
  Apoptotic Factor-Mediated Response
  Class I Peroxisomal Membrane Protein Import
  Synthesis of Leukotrienes (LT) and Eoxins (EX)
  Vitamin B5 (Pantothenate) Metabolism
  Positive Epigenetic Regulation of rRNA Expression
  Cell Death Signalling via NRAGE, NRIF and NADE
  Generic Transcription Pathway
  ZBP1(DAI) Mediated Induction of Type I IFNs
  Negative Regulation of NMDA Receptor-Mediated Neuronal Transmission
  Synaptic Adhesion-Like Molecules
  Interleukin-37 Signaling
  Unblocking of NMDA Receptors, Glutamate Binding and Activation
  Bacterial Infection Pathways
  Diseases of Programmed Cell Death
  Vesicle-mediated Transport
  Blood Group Systems Biosynthesis
  Regulation of TLR by Endogenous Ligand
  ERK MAPK Targets
  SHC1 Events in ERBB2 Signaling
  RNA Polymerase I Promoter Clearance
  G Alpha (12 13) Signalling Events
  G Alpha (Q) Signalling Events
  Suppression of Phagosomal Maturation
  Long-term Potentiation
  RNA Polymerase I Transcription
  Senescence-Associated Secretory Phenotype (SASP)
  Other Interleukin Signaling
  CD28 Dependent PI3K Akt Signaling
  G-protein Activation
  Glutamate Neurotransmitter Release Cycle
  Growth Hormone Receptor Signaling
  Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers
  Transcriptional Regulation of White Adipocyte Differentiation
  RUNX1 Regulates Transcription of Genes Involved in Differentiation of HSCs
  Integrin Cell Surface Interactions
  NOTCH3 Intracellular Domain Regulates Transcription
  Signaling by NTRK2 (TRKB)
  Inflammasomes
  Insulin Processing
  Metabolism of Cofactors
  Peptide Hormone Metabolism
  Endogenous Sterols
  HDMs Demethylate Histones
  Synthesis of IP3 and IP4 in the Cytosol
  Interleukin-20 Family Signaling
  Translocation of ZAP-70 to Immunological Synapse
  Miscellaneous Transport and Binding Events
  Death Receptor Signaling
  Protein-protein Interactions at Synapses
  Pre-NOTCH Expression and Processing
  Cardiogenesis
  Pyroptosis
  Regulation of RUNX1 Expression and Activity
  RAB GEFs Exchange GTP for GDP on RABs
  Downstream TCR Signaling
  Notch-HLH Transcription Pathway
  Peroxisomal Lipid Metabolism
  Platelet Calcium Homeostasis
  Keratan Sulfate Biosynthesis
  Metabolism of Porphyrins
  Chromatin Modifying Enzymes
  Chromatin Organization
  Protein Localization
  Post-translational Modification Synthesis of GPI-anchored Proteins
  Cellular Responses to Mechanical Stimuli
  Response of Endothelial Cells to Shear Stress
  Signaling by ALK Fusions and Activated Point Mutants
  Signaling by ALK in Cancer
  Myogenesis
  Acyl Chain Remodelling of PE
  The Role of Nef in HIV-1 Replication and Disease Pathogenesis
  Oxidative Stress Induced Senescence
  Class B 2 (Secretin Family Receptors)
  Cellular Senescence
  Activation of BH3-only Proteins
  Activation of Kainate Receptors Upon Glutamate Binding
  Regulation of TP53 Activity Through Acetylation
  Intracellular Signaling by Second Messengers
  Antigen processing-Cross Presentation
  Mitochondrial Biogenesis
  Nicotinate Metabolism
  FOXO-mediated Transcription of Oxidative Stress, Metabolic and Neuronal Genes
  Transcriptional Regulation of Brown and Beige Adipocyte Differentiation
  Transcriptional Regulation of Brown and Beige Adipocyte Differentiation by EBF2
  MAPK Targets Nuclear Events Mediated by MAP Kinases
  Turbulent Flow Shear Stress Activates Signaling by PIEZO1 and Integrins in Endothelial Cells
  Metalloprotease DUBs
  Metabolism of Nucleotides
  Nuclear Signaling by ERBB4
  Regulation of Necroptotic Cell Death
  Amino Acid Transport Across the Plasma Membrane
  Glucagon-type Ligand Receptors
  RIPK1-mediated Regulated Necrosis
  Diseases of Carbohydrate Metabolism
  Negative Regulators of DDX58 IFIH1 Signaling
  Oncogene Induced Senescence
  Diseases Associated With the TLR Signaling Cascade
  Diseases of Immune System
  Cargo Recognition for Clathrin-Mediated Endocytosis
  Aberrant Regulation of Mitotic Cell Cycle Due to RB1 Defects
  RHO GTPases Activate WASPs and WAVEs
  Signaling by NOTCH2
  Signaling by High-Kinase Activity BRAF Mutants
  Striated Muscle Contraction
  Keratan Sulfate Keratin Metabolism
  Metabolism of Steroid Hormones
  Metabolism of Lipids
  Disease
  RUNX1 Interacts With Co-Factors Whose Precise Effect on RUNX1 Targets Is Not Known
  Evasion by RSV of Host Interferon Responses
  Gene and Protein Expression by JAK-STAT Signaling After Interleukin-12 Stimulation
  RNA Polymerase II Transcription
  Diseases of Mitotic Cell Cycle
  Regulation of Endogenous Retroelements
  Chromatin Modifications During the Maternal to Zygotic Transition (MZT)
  Response of Mtb to Phagocytosis
  Glycosphingolipid Catabolism
  Synthesis of PA
  RHOU GTPase Cycle
  MAP2K and MAPK Activation
  Signaling by NTRK1 (TRKA)
  DAG and IP3 Signaling
  Defective Pyroptosis
  Signaling by RAF1 Mutants
  Transcriptional Regulation by VENTX
  Developmental Biology
  NCAM1 Interactions
  EPHB-mediated Forward Signaling
  Formation of WDR5-containing Histone-Modifying Complexes
  Peptide Ligand-Binding Receptors
  Metabolism of Vitamins and Cofactors
  PIP3 Activates AKT Signaling
  Aspirin ADME
  Assembly and Cell Surface Presentation of NMDA Receptors
  Transport of Vitamins, Nucleosides, and Related Molecules
  Voltage Gated Potassium Channels
  Collagen Chain Trimerization
  Estrogen-dependent Gene Expression
  Paradoxical Activation of RAF Signaling by Kinase Inactive BRAF
  Regulation of RUNX3 Expression and Activity
  ERCC6 (CSB) and EHMT2 (G9a) Positively Regulate rRNA Expression
  Signaling by RAS Mutants
  Signaling by Moderate Kinase Activity BRAF Mutants
  Signaling Downstream of RAS Mutants
  TBC RABGAPs
  Muscle Contraction
  Class I MHC Mediated Antigen Processing & Presentation
  NIK-->noncanonical NF-kB Signaling
  PKMTs Methylate Histone Lysines
  Interleukin-12 Signaling
  Kidney Development
  Epigenetic Regulation of Gene Expression
  Cyclin D Associated Events in G1
  G1 Phase
  Signaling by NOTCH
  Metabolism of Water-Soluble Vitamins and Cofactors
  NOTCH1 Intracellular Domain Regulates Transcription
  Inositol Phosphate Metabolism
  Glycerophospholipid Biosynthesis
  GPCR Ligand Binding
  Dectin-1 Mediated Noncanonical NF-kB Signaling
  Retrograde Transport at the Trans-Golgi-Network
  Signaling by NOTCH3
  Cardiac Conduction
  Signaling by ERBB2
  Gene Expression (Transcription)
  Neurotransmitter Release Cycle
  Nonhomologous End-Joining (NHEJ)
  Signaling by NTRKs
  COPI-independent Golgi-to-ER Retrograde Traffic
  Proteasome Assembly
  Epigenetic Regulation by WDR5-containing Histone Modifying Complexes
  Signaling by EGFR
  Immunoregulatory Interactions Between a Lymphoid and a non-Lymphoid Cell
  SARS-CoV-1 Activates Modulates Innate Immune Responses
  Ion Homeostasis
  SARS-CoV-2 Activates Modulates Innate and Adaptive Immune Responses
  Regulation of RAS by GAPs
  Signaling by Non-Receptor Tyrosine Kinases
  Signaling by PTK6
  Ion Transport by P-type ATPases
  MAPK Family Signaling Cascades
  Interleukin-12 Family Signaling
  G Alpha (I) Signalling Events
  Chemokine Receptors Bind Chemokines
  Regulation of Actin Dynamics for Phagocytic Cup Formation
  Constitutive Signaling by NOTCH1 HD+PEST Domain Mutants
  Constitutive Signaling by NOTCH1 PEST Domain Mutants
  SUMOylation of Chromatin Organization Proteins
  Signaling by ERBB4
  Signaling by NOTCH1 HD+PEST Domain Mutants in Cancer
  Signaling by NOTCH1 PEST Domain Mutants in Cancer
  Signaling by NOTCH1 in Cancer
  Glycosphingolipid Metabolism
  Transcriptional Regulation of Granulopoiesis
  Clathrin-mediated Endocytosis
  Neuronal System
  Arachidonate Metabolism
  B-WICH Complex Positively Regulates rRNA Expression
  Regulation of RUNX2 Expression and Activity
  Formation of Paraxial Mesoderm
  Formation of the Beta-Catenin TCF Transactivating Complex
  HDACs Deacetylate Histones
  Infectious Disease
  RHOA GTPase Cycle
  Nuclear Events (Kinase and Transcription Factor Activation)
  Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways
  Regulation of PTEN Gene Transcription
  Gamma Carboxylation, Hypusinylation, Hydroxylation, and Arylsulfatase Activation
  NCAM Signaling for Neurite Out-Growth
  Peroxisomal Protein Import
  Class A 1 (Rhodopsin-like Receptors)
  Collagen Degradation
  CDC42 GTPase Cycle
  RAB Geranylgeranylation
  Cytochrome P450 - Arranged by Substrate Type
  RUNX1 Regulates Genes Involved in Megakaryocyte Differentiation and Platelet Function
  Signaling by BRAF and RAF1 Fusions
  Mitochondrial Protein Import
  G Alpha (S) Signalling Events
  Collagen Biosynthesis and Modifying Enzymes
  Regulation of TP53 Activity
  High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell
  CD22 Mediated BCR Regulation
  RHOB GTPase Cycle
  Translocation of SLC2A4 (GLUT4) to the Plasma Membrane
  Signaling by NOTCH4
  Transport of Small Molecules
  Pre-NOTCH Transcription and Translation
  Hedgehog 'On' State
  RHO GTPase Cycle
  RHOG GTPase Cycle
  Signaling by NOTCH1
  RAF MAP Kinase Cascade
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  ISG15 Antiviral Mechanism
  Deubiquitination
  Transmission Across Chemical Synapses
  MAPK1 MAPK3 Signaling
  Fatty Acid Metabolism
  Amyloid Fiber Formation
  Post NMDA Receptor Activation Events

/opt/anaconda3/envs/enhancer3D/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

==========================================================================================
H1ESC small vs GM12878 mid/large   (297 genes, 748 reactome terms)
==========================================================================================
  Neuronal System
  Transmission Across Chemical Synapses
  Neurotransmitter Receptors and Postsynaptic Signal Transmission
  Epithelial-Mesenchymal Transition (EMT) During Gastrulation
  Laminin Interactions
  Repression of WNT Target Genes
  Extracellular Matrix Organization
  SUMOylation of DNA Methylation Proteins
  EPH-Ephrin Signaling
  Activation of NMDA Receptors and Postsynaptic Events
  Ras Activation Upon Ca2+ Influx Through NMDA Receptor
  VLDL Clearance
  High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell
  RHO GTPases Activate PAKs
  Activation of GABAB Receptors
  GABA B Receptor Activation
  SHC1 Events in ERBB2 Signaling
  G Alpha (Z) Signalling Events
  Post NMDA Receptor Activation Events
  EGFR Transactivation by Gastrin
  Cell Junction Organization
  CREB1 Phosphorylation Through NMDA Receptor-Mediated Activation of RAS Signaling
  Signaling by Rho GTPases
  Adenylate Cyclase Activating Pathway
  Neurexins and Neuroligins
  Signaling by Rho GTPases, Miro GTPases and RHOBTB3
  Tight Junction Interactions
  Non-integrin membrane-ECM Interactions
  Cell-cell Junction Organization
  TGFBR3 PTM Regulation
  GABA Receptor Activation
  Axon Guidance
  Cellular Responses to Mechanical Stimuli
  Response of Endothelial Cells to Shear Stress
  Activation of Matrix Metalloproteinases
  Glucagon Signaling in Metabolic Regulation
  Ca2+ Pathway
  CaM Pathway
  Calmodulin Induced Events
  Degradation of the Extracellular Matrix
  Signal Transduction
  Nervous System Development
  Ca-dependent Events
  Adenylate Cyclase Inhibitory Pathway
  PTK6 Regulates RHO GTPases, RAS GTPase and MAP Kinases
  Defective EXT1 Causes Exostoses 1, TRPS2 and CHDS
  Defective EXT2 Causes Exostoses 2
  SHC1 Events in ERBB4 Signaling
  IRAK1 Recruits IKK Complex
  IRAK1 Recruits IKK Complex Upon TLR7 8 or 9 Stimulation
  Synthesis of IP2, IP, and Ins in the Cytosol
  Clathrin-mediated Endocytosis
  Response of EIF2AK1 (HRI) to Heme Deficiency
  Integration of Energy Metabolism
  RET Signaling
  DAG and IP3 Signaling
  Diseases Associated With Glycosaminoglycan Metabolism
  GRB2 Events in ERBB2 Signaling
  Deactivation of the Beta-Catenin Transactivating Complex
  EPHB-mediated Forward Signaling
  ECM Proteoglycans
  ADORA2B Mediated Anti-Inflammatory Cytokines Production
  Signaling by SCF-KIT
  Vasopressin Regulates Renal Water Homeostasis via Aquaporins
  PKA Activation in Glucagon Signalling
  Trafficking of GluR2-containing AMPA Receptors
  Smooth Muscle Contraction
  Cell-Cell Communication
  GPER1 Signaling
  PKA Activation
  Gastrin-CREB Signalling Pathway via PKC and MAPK
  RHO GTPase Cycle
  Gastrulation
  RHO GTPases Activate ROCKs
  RHO GTPases Activate CIT
  VEGFR2 Mediated Cell Proliferation
  Gap Junction Trafficking
  PLC Beta Mediated Events
  PKA-mediated Phosphorylation of CREB
  Defective B3GALT6 Causes EDSP2 and SEMDJL1
  Defective B3GAT3 Causes JDSSDHD
  Defective B4GALT7 Causes EDS, Progeroid Type
  Sema4D Induced Cell Migration and Growth-Cone Collapse
  Platelet Activation, Signaling and Aggregation
  Chondroitin Sulfate Dermatan Sulfate Metabolism
  Signaling by ERBB2
  RAF MAP Kinase Cascade
  SHC-mediated Cascade FGFR1
  Gap Junction Trafficking and Regulation
  Protein-protein Interactions at Synapses
  Aquaporin-mediated Transport
  Signaling by ERBB2 TMD JMD Mutants
  Opioid Signalling
  MAPK1 MAPK3 Signaling
  Response to Elevated Platelet Cytosolic Ca2+
  G-protein Mediated Events
  Insulin Receptor Signalling Cascade
  FRS-mediated FGFR1 Signaling
  Beta-catenin Independent WNT Signaling
  Signaling by Non-Receptor Tyrosine Kinases
  Signaling by PTK6
  Sema4D in Semaphorin Signaling
  Glutamate Neurotransmitter Release Cycle
  HS-GAG Degradation
  RAC1 GTPase Cycle
  Signaling by ERBB2 KD Mutants
  Signaling by NTRK2 (TRKB)
  Signaling by WNT
  A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis
  Attachment and Entry 9694614
  Signaling by ERBB2 in Cancer
  Formation of the Beta-Catenin TCF Transactivating Complex
  Acyl Chain Remodelling of PC
  Syndecan Interactions
  Integrin Signaling
  Diseases of Glycosylation
  NCAM Signaling for Neurite Out-Growth
  Cargo Recognition for Clathrin-Mediated Endocytosis
  Semaphorin Interactions
  Activation of G Protein Gated Potassium Channels
  Acyl Chain Remodelling of PE
  Downstream Signal Transduction
  EPHA-mediated Growth Cone Collapse
  G Protein Gated Potassium Channels
  Inhibition of Voltage Gated Ca2+ Channels via Gbeta Gamma Subunits
  Activation of Kainate Receptors Upon Glutamate Binding
  Activation of RAS in B Cells
  Reelin Signalling Pathway
  Disinhibition of SNARE Formation
  Electric Transmission Across Gap Junctions
  Formation of the Active Cofactor, UDP-glucuronate
  Sodium-coupled Sulphate, Di- and Tri-Carboxylate Transporters
  IRS Activation
  Transmission Across Electrical Synapses
  VLDL Assembly
  Downregulation of SMAD2 3 SMAD4 Transcriptional Activity
  Downstream Signaling of Activated FGFR1
  Glutamate Binding, Activation of AMPA Receptors and Synaptic Plasticity
  HS-GAG Biosynthesis
  Trafficking of AMPA Receptors
  Phase II - Conjugation of Compounds
  Respiratory Syncytial Virus (RSV) Attachment and Entry
  MAPK Family Signaling Cascades
  Diseases of Metabolism
  Degradation of Beta-Catenin by the Destruction Complex
  Conjugation of Benzoate With Glycine
  Estrogen-stimulated Signaling Through PRKCZ
  SARS-CoV-2 Targets PDZ Proteins in Cell-Cell Junction
  Intracellular Signaling by Second Messengers
  Signaling by NOTCH1
  Inwardly Rectifying K+ Channels
  Cellular Senescence
  Signaling by High-Kinase Activity BRAF Mutants
  Wax and Plasmalogen Biosynthesis
  Activated NTRK2 Signals Through FYN
  Nectin Necl Trans Heterodimerization
  RAS Signaling Downstream of NF1 Loss-Of-Function Variants
  Constitutive Signaling by NOTCH1 t(7;9)(NOTCH1 M1580 K2555) Translocation Mutant
  SOS-mediated Signalling
  Signaling by NOTCH1 t(7;9)(NOTCH1 M1580 K2555) Translocation Mutant
  Plasma Lipoprotein Clearance
  RUNX1 Interacts With Co-Factors Whose Precise Effect on RUNX1 Targets Is Not Known
  Gap Junction Assembly
  Regulation of Insulin Secretion
  Apoptotic Cleavage of Cellular Proteins
  Defective B3GALTL Causes PpS
  FLT3 Signaling
  Signaling by FGFR1 in Disease
  Signaling by MET
  O-glycosylation of TSR Domain-Containing Proteins
  Platelet Aggregation (Plug Formation)
  Glycosaminoglycan Metabolism
  Activated NTRK3 Signals Through RAS
  Binding of TCF LEF CTNNB1 to Target Gene Promoters
  Conjugation of Salicylate With Glycine
  Defective CHST6 Causes MCDC1
  RUNX3 Regulates WNT Signaling
  Defects in Biotin (Btn) Metabolism
  FGFR1b Ligand Binding and Activation
  Metabolism of Ingested SeMet, Sec, MeSec Into H2Se
  Platelet Degranulation
  MAP2K and MAPK Activation
  Signaling by Insulin Receptor
  Signaling by RAF1 Mutants
  RHOF GTPase Cycle
  Glucagon-like Peptide-1 (GLP1) Regulates Insulin Secretion
  Integrin Cell Surface Interactions
  RHO GTPase Effectors
  Activated NTRK2 Signals Through RAS
  Amino Acid Conjugation
  CREB3 Factors Activate Genes
  Conjugation of Carboxylic Acids
  RHO GTPases Activate Rhotekin and Rhophilins
  ROBO Receptors Bind AKAP5
  SHC-related Events Triggered by IGF1R
  Formyl Peptide Receptors Bind Formyl Peptides and Many Other Ligands
  Transcriptional Regulation by RUNX3
  Developmental Biology
  Assembly and Cell Surface Presentation of NMDA Receptors
  Netrin-1 Signaling
  Retinoid Metabolism and Transport
  SUMOylation of Transcription Cofactors
  Hemostasis
  Paradoxical Activation of RAF Signaling by Kinase Inactive BRAF
  Carboxyterminal Post-Translational Modifications of Tubulin
  Signaling by RAS Mutants
  Signaling by Moderate Kinase Activity BRAF Mutants
  Signaling Downstream of RAS Mutants
  Zinc Influx Into Cells by the SLC39 Gene Family
  Acetylcholine Regulates Insulin Secretion
  Activation of Ca-permeable Kainate Receptor
  PI3K Events in ERBB4 Signaling
  RUNX3 Regulates p14-ARF
  Formation of the Posterior Neural Plate
  Signal Attenuation
  HuR (ELAVL1) Binds and Stabilizes mRNA
  InlA-mediated Entry of Listeria Monocytogenes Into Host Cells
  Ionotropic Activity of Kainate Receptors
  Thyroxine Biosynthesis
  Early SARS-CoV-2 Infection Events
  Kidney Development
  Signaling by FGFR
  SUMOylation of RNA Binding Proteins
  Mucopolysaccharidoses
  Activated NTRK2 Signals Through FRS2 and FRS3
  NOTCH4 Activation and Transmission of Signal to the Nucleus
  Apoptotic Cleavage of Cell Adhesion Proteins
  Biotin Transport and Metabolism
  RHO GTPases Activate KTN1
  Constitutive Signaling by Overexpressed ERBB2
  Regulation of the Apoptosome Activity
  Formation of Annular Gap Junctions
  Formation of Apoptosome
  Formation of the Anterior Neural Plate
  Signaling by FGFR4 in Disease
  Signaling by Activated Point Mutants of FGFR1
  Sodium Calcium Exchangers
  MET Activates RAS Signaling
  NOTCH1 Intracellular Domain Regulates Transcription
  IRS-mediated Signalling
  Inositol Phosphate Metabolism
  Metabolism of Fat-Soluble Vitamins
  RAC3 GTPase Cycle
  Signaling by TGFBR3
  Aspartate and Asparagine Metabolism
  Organic Anion Transporters
  Butyrophilin (BTN) Family Interactions
  CREB1 Phosphorylation Through the Activation of Adenylate Cyclase
  Caspase-mediated Cleavage of Cytoskeletal Proteins
  Gap Junction Degradation
  Signaling by PDGFRA Extracellular Domain Mutants
  Signaling by PDGFRA Transmembrane, Juxtamembrane and Kinase Domain Mutants
  Hyaluronan Uptake and Degradation
  Lysine Catabolism
  RHOA GTPase Cycle
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  Neurotransmitter Release Cycle
  EPH-ephrin Mediated Repulsion of Cells
  Transcriptional Activity of SMAD2 SMAD3 SMAD4 Heterotrimer
  VEGFA-VEGFR2 Pathway
  Visual Phototransduction
  Apoptotic Execution Phase
  Signaling by FGFR1
  IRS-related Events Triggered by IGF1R
  WNT5A-dependent Internalization of FZD2, FZD5 and ROR2
  eNOS Activation
  p38MAPK Events
  Nephron Development
  Advanced Glycosylation Endproduct Receptor Signaling
  Cytochrome C-Mediated Apoptotic Response
  Dissolution of Fibrin Clot
  ERBB2 Activates PTK6 Signaling
  GRB2 Events in EGFR Signaling
  Glutathione Synthesis and Recycling
  Telomere C-strand Synthesis Initiation
  Signaling by EGFR
  IGF1R Signaling Cascade
  Interleukin-1 Signaling
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R)
  MyD88 Dependent Cascade Initiated on Endosome
  Potassium Channels
  CS DS Degradation
  DCC Mediated Attractive Signaling
  RUNX3 Regulates NOTCH Signaling
  Erythropoietin Activates RAS
  FGFR1c Ligand Binding and Activation
  SHC1 Events in EGFR Signaling
  Glycogen Synthesis
  Lysosphingolipid and LPA Receptors
  Regulation of RAS by GAPs
  Sensory Processing of Sound by Outer Hair Cells of the Cochlea
  WNT5A-dependent Internalization of FZD4
  Zinc Transporters
  p130Cas Linkage to MAPK Signaling for Integrins
  Constitutive Signaling by EGFRvIII
  Constitutive Signaling by NOTCH1 HD Domain Mutants
  Depolymerization of the Nuclear Lamina
  ERBB2 Regulates Cell Motility
  Signaling by EGFRvIII in Cancer
  Signaling by NOTCH1 HD Domain Mutants in Cancer
  Heparan Sulfate Heparin (HS-GAG) Metabolism
  Post-translational Protein Phosphorylation
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Transport of Inorganic Cations Anions and Amino Acids Oligopeptides
  Signaling by TGFB Family Members
  Signaling by VEGF
  SUMOylation of Chromatin Organization Proteins
  Signaling by ERBB4
  Signaling by PDGF
  G Alpha (Q) Signalling Events
  Adherens Junctions Interactions
  Toll Like Receptor 9 (TLR9) Cascade
  PI3K Events in ERBB2 Signaling
  CRMPs in Sema3A Signaling
  Phospholipase C-mediated Cascade FGFR1
  Rap1 Signalling
  Regulation of KIT Signaling
  Signaling by ERBB2 ECD Mutants
  Signaling by FLT3 ITD and TKD Mutants
  VLDLR Internalisation and Degradation
  DNA Damage Telomere Stress Induced Senescence
  Regulation of PTEN Gene Transcription
  Acetylcholine Neurotransmitter Release Cycle
  Acyl Chain Remodelling of PI
  Purine Catabolism
  Regulation of MITF-M-dependent Genes Involved in Cell Cycle and Proliferation
  Removal of the Flap Intermediate From the C-strand
  Formation of Senescence-Associated Heterochromatin Foci (SAHF)
  Signaling by NTRK3 (TRKC)
  Specification of the Neural Plate Border
  Hyaluronan Metabolism
  IL-6-type Cytokine Receptor Ligand Interactions
  The NLRP3 Inflammasome
  Metabolism of Nitric Oxide NOS3 Activation and Regulation
  O-linked Glycosylation
  RHO GTPases Activate PKNs
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  Signaling by FGFR in Disease
  Norepinephrine Neurotransmitter Release Cycle
  Cell-extracellular Matrix Interactions
  FGFR1 Ligand Binding and Activation
  SHC-mediated Cascade FGFR3
  Formation of Definitive Endoderm
  Serotonin Neurotransmitter Release Cycle
  G Beta Gamma Signalling Through BTK
  Tie2 Signaling
  MECP2 Regulates Neuronal Receptors and Channels
  Metabolism of Amine-Derived Hormones
  Signaling by Receptor Tyrosine Kinases
  Metabolism of Carbohydrates
  Collagen Degradation
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Signaling by BRAF and RAF1 Fusions
  Plasma Lipoprotein Assembly
  Processive Synthesis on the C-strand of the Telomere
  Prostacyclin Signalling Through Prostacyclin Receptor
  Constitutive Signaling by Ligand-Responsive EGFR Cancer Variants
  Ephrin Signaling
  SARS-CoV-1 Targets Host Intracellular Signalling and Regulatory Pathways
  Signaling by FLT3 Fusion Proteins
  Signaling by Ligand-Responsive EGFR Variants in Cancer
  Apoptotic Factor-Mediated Response
  SHC-mediated Cascade FGFR4
  FRS-mediated FGFR3 Signaling
  G Beta Gamma Signalling Through CDC42
  G Beta Gamma Signalling Through PLC Beta
  Signaling by KIT in Disease
  Signaling by PDGFR in Disease
  Signaling by Phosphorylated Juxtamembrane, Extracellular and Kinase Domain KIT Mutants
  Signalling to RAS
  Sensory Processing of Sound by Inner Hair Cells of the Cochlea
  Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs)
  Negative Regulation of MET Activity
  Negative Regulation of NMDA Receptor-Mediated Neuronal Transmission
  PI-3K Cascade FGFR1
  CD209 (DC-SIGN) Signaling
  Presynaptic Function of Kainate Receptors
  Digestion
  Formation of the Ureteric Bud
  Signal Transduction by L1
  Synaptic Adhesion-Like Molecules
  Synthesis, Secretion, and Inactivation of Glucagon-like Peptide-1 (GLP-1)
  Unblocking of NMDA Receptors, Glutamate Binding and Activation
  RHOB GTPase Cycle
  Diseases Associated With O-glycosylation of Proteins
  ADP Signalling Through P2Y Purinoceptor 12
  Acyl Chain Remodelling of PS
  Neurodegenerative Diseases
  Chaperone Mediated Autophagy
  Defects in Vitamin and Cofactor Metabolism
  Deregulated CDK5 Triggers Multiple Neurodegenerative Pathways in Alzheimer's Disease Models
  FRS-mediated FGFR4 Signaling
  Signaling by FGFR3 in Disease
  Insertion of Tail-Anchored Proteins Into the Endoplasmic Reticulum Membrane
  Listeria Monocytogenes Entry Into Host Cells
  Cellular Responses to Stimuli
  SLC-mediated Transmembrane Transport
  TCF Dependent Signaling in Response to WNT
  Azathioprine ADME
  Dopamine Neurotransmitter Release Cycle
  SHC-mediated Cascade FGFR2
  Telomere Extension By Telomerase
  Long-term Potentiation
  Plasma Lipoprotein Assembly, Remodeling, and Clearance
  Extra-nuclear Estrogen Signaling
  Signaling by FGFR2
  RAS Processing
  RHO GTPases Activate NADPH Oxidases
  Cytosolic Sulfonation of Small Molecules
  RUNX2 Regulates Osteoblast Differentiation
  G-protein Activation
  Incretin Synthesis, Secretion, and Inactivation
  Synthesis of Very Long-Chain Fatty acyl-CoAs
  Interleukin-6 Family Signaling
  Thromboxane Signalling Through TP Receptor
  Metal Ion SLC Transporters
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  SUMOylation of DNA Damage Response and Repair Proteins
  Sensory Processing of Sound
  ADP Signalling Through P2Y Purinoceptor 1
  NOTCH2 Activation and Transmission of Signal to the Nucleus
  NOTCH3 Activation and Transmission of Signal to the Nucleus
  Defective Intrinsic Pathway for Apoptosis
  Downstream Signaling of Activated FGFR3
  FRS-mediated FGFR2 Signaling
  G Beta Gamma Signalling Through PI3Kgamma
  Signaling by EGFR in Cancer
  Signaling by Erythropoietin
  Glycogen Metabolism
  Inflammasomes
  TRAF6 Mediated NF-kB Activation
  Diseases of Programmed Cell Death
  PCP CE Pathway
  Polymerase Switching on the C-strand of the Telomere
  Digestion and Absorption
  Gluconeogenesis
  Glucuronidation
  Amyloid Fiber Formation
  G Alpha (12 13) Signalling Events
  Interleukin-1 Family Signaling
  Cell Recruitment (Pro-Inflammatory Response)
  Purinergic Signaling in Leishmaniasis Infection
  Downstream Signaling of Activated FGFR4
  Oncogenic MAPK Signaling
  Muscle Contraction
  Transport of Small Molecules
  Constitutive Signaling by Aberrant PI3K in Cancer
  Activation of AMPK Downstream of NMDARs
  Adrenaline,noradrenaline Inhibits Insulin Secretion
  BMAL1 CLOCK,NPAS2 Activates Circadian Gene Expression
  FGFR2 Alternative Splicing
  FLT3 Signaling in Disease
  Sulfur Amino Acid Metabolism
  Keratan Sulfate Biosynthesis
  Transport of Bile Salts and Organic Acids, Metal Ions and Amine Compounds
  PTEN Regulation
  Myogenesis
  DAP12 Signaling
  Downregulation of ERBB2 Signaling
  Toll Like Receptor 4 (TLR4) Cascade
  Downstream Signaling of Activated FGFR2
  Signaling by CSF3 (G-CSF)
  Interconversion of Nucleotide Di- and Triphosphates
  MET Activates PTK2 Signaling
  Activated NOTCH1 Transmits Signal to the Nucleus
  RHO GTPases Activate IQGAPs
  RUNX2 Regulates Bone Development
  FGFR1 Mutant Receptor Activation
  Signaling by BMP
  Signaling by CSF1 (M-CSF) in Myeloid Cells
  Transcriptional Regulation of Brown and Beige Adipocyte Differentiation
  Transcriptional Regulation of Brown and Beige Adipocyte Differentiation by EBF2
  Turbulent Flow Shear Stress Activates Signaling by PIEZO1 and Integrins in Endothelial Cells
  Metabolism
  PIP3 Activates AKT Signaling
  Nuclear Signaling by ERBB4
  Packaging Of Telomere Ends
  G-protein Beta Gamma Signalling
  Thrombin Signalling Through Proteinase Activated Receptors (PARs)
  Transcriptional Regulation of Pluripotent Stem Cells
  Chaperonin-mediated Protein Folding
  Negative Regulation of FGFR1 Signaling
  DNA Methylation
  Signal Amplification
  Glucagon-type Ligand Receptors
  Synthesis of Bile Acids and Bile Salts
  Inactivation, Recovery and Regulation of the Phototransduction Cascade
  Biological Oxidations
  RAF Activation
  Diseases of Carbohydrate Metabolism
  Signaling by WNT in Cancer
  Signalling to ERKs
  Telomere C-strand (Lagging Strand) Synthesis
  The Phototransduction Cascade
  Late Endosomal Microautophagy
  Transcriptional Regulation by E2F6
  Oxidative Stress Induced Senescence
  Signaling by TGF-beta Receptor Complex
  G Alpha (S) Signalling Events
  Unfolded Protein Response (UPR)
  Anti-inflammatory Response Favouring Leishmania Parasite Infection
  Leishmania Parasite Growth and Survival
  Nucleotide Catabolism
  Oncogene Induced Senescence
  Lysosome Vesicle Biogenesis
  Metabolism of Amino Acids and Derivatives
  Protein Folding
  Cleavage of the Damaged Purine
  Recognition and Association of DNA Glycosylase With Site Containing an Affected Purine
  Depurination

/opt/anaconda3/envs/enhancer3D/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

==========================================================================================
H1ESC small vs HFFC6 mid/large   (310 genes, 633 reactome terms)
==========================================================================================
  IRS Activation
  Semaphorin Interactions
  Other Semaphorin Interactions
  AKT Phosphorylates Targets in the Nucleus
  Adenylate Cyclase Activating Pathway
  Regulation of FOXO Transcriptional Activity by Acetylation
  Signal Attenuation
  Regulation of Localization of FOXO Transcription Factors
  Reversible Hydration of Carbon Dioxide
  RHO GTPase Cycle
  Nephron Development
  Adenylate Cyclase Inhibitory Pathway
  RAC1 GTPase Cycle
  High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell
  VLDLR Internalisation and Degradation
  Vasopressin Regulates Renal Water Homeostasis via Aquaporins
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  CDC42 GTPase Cycle
  PKA Activation in Glucagon Signalling
  Signaling by MET
  PKA Activation
  Kidney Development
  Signaling by Rho GTPases
  PKA-mediated Phosphorylation of CREB
  Sema4D Induced Cell Migration and Growth-Cone Collapse
  Glycerophospholipid Biosynthesis
  Aquaporin-mediated Transport
  Signaling by Rho GTPases, Miro GTPases and RHOBTB3
  Cell-cell Junction Organization
  Signaling by Non-Receptor Tyrosine Kinases
  Signaling by PTK6
  Cellular Responses to Mechanical Stimuli
  Response of Endothelial Cells to Shear Stress
  Sema4D in Semaphorin Signaling
  Neurexins and Neuroligins
  Constitutive Signaling by AKT1 E17K in Cancer
  GABA Receptor Activation
  Synthesis of PC
  RHOA GTPase Cycle
  G1 S-Specific Transcription
  The Role of Nef in HIV-1 Replication and Disease Pathogenesis
  Integration of Energy Metabolism
  NR1H2 & NR1H3 Regulate Gene Expression to Limit Cholesterol Uptake
  Defective LFNG Causes SCDO3
  Reelin Signalling Pathway
  Serotonin and Melatonin Biosynthesis
  Signaling by MST1
  Signaling by Membrane-Tethered Fusions of PDGFRA or PDGFRB
  Sodium-coupled Sulphate, Di- and Tri-Carboxylate Transporters
  MET Interacts With TNS Proteins
  FOXO-mediated Transcription
  Neuronal System
  RHO GTPases Activate IQGAPs
  FOXO-mediated Transcription of Oxidative Stress, Metabolic and Neuronal Genes
  Generic Transcription Pathway
  Regulation of Endogenous Retroelements
  Signal Transduction
  Glucagon Signaling in Metabolic Regulation
  Diseases Associated With O-glycosylation of Proteins
  Pre-NOTCH Processing in the Endoplasmic Reticulum
  LTC4-CYSLTR Mediated IL4 Production
  MET Receptor Activation
  VLDL Clearance
  Signaling by Receptor Tyrosine Kinases
  CaM Pathway
  Calmodulin Induced Events
  Lysosome Vesicle Biogenesis
  Intracellular Signaling by Second Messengers
  Cell Junction Organization
  Transmission Across Chemical Synapses
  CREB Phosphorylation
  Coenzyme A Biosynthesis
  Epithelial-Mesenchymal Transition (EMT) During Gastrulation
  Glycine Degradation
  Ca-dependent Events
  Plasma Lipoprotein Clearance
  Defective B3GALTL Causes PpS
  Host Interactions of HIV Factors
  Post NMDA Receptor Activation Events
  O-glycosylation of TSR Domain-Containing Proteins
  Synthesis of PA
  AMPK Inhibits chREBP Transcriptional Activation Activity
  Noncanonical Activation of NOTCH3
  CDC6 Association With the ORC Origin Complex
  Defective CHST6 Causes MCDC1
  Sema4D Mediated Inhibition of Cell Attachment and Migration
  Insulin-like Growth Factor-2 mRNA Binding Proteins (IGF2BPs IMPs VICKZs) Bind RNA
  Linoleic Acid (LA) Metabolism
  VEGF Binds to VEGFR Leading to Receptor Dimerization
  VEGF Ligand-Receptor Interactions
  Vpr-mediated Nuclear Import of PICs
  Regulation of HSF1-mediated Heat Shock Response
  DAG and IP3 Signaling
  MET Promotes Cell Motility
  RND1 GTPase Cycle
  Nef and Signal Transduction
  Autointegration Results in Viral DNA Circles
  RHO GTPases Activate Rhotekin and Rhophilins
  E2F-enabled Inhibition of Pre-Replication Complex Formation
  Sperm Motility And Taxes
  Integration of Viral DNA Into Host Genomic DNA
  Interleukin-23 Signaling
  Lipophagy
  Epigenetic Regulation of Gene Expression
  ADORA2B Mediated Anti-Inflammatory Cytokines Production
  Activation of GABAB Receptors
  GABA B Receptor Activation
  Interactions of Vpr With Host Cellular Proteins
  Protein-protein Interactions at Synapses
  Antigen Processing Ubiquitination & Proteasome Degradation
  Activation of PPARGC1A (PGC-1alpha) by Phosphorylation
  PI3K Events in ERBB4 Signaling
  Creatine Metabolism
  FGFR2b Ligand Binding and Activation
  InlA-mediated Entry of Listeria Monocytogenes Into Host Cells
  GPER1 Signaling
  SUMOylation of RNA Binding Proteins
  APOBEC3G Mediated Resistance to HIV-1 Infection
  Nef Mediated Downregulation of MHC Class I Complex Cell Surface Expression
  Apoptotic Cleavage of Cell Adhesion Proteins
  Regulation of Gene Expression by Hypoxia-inducible Factor
  Activation of NMDA Receptors and Postsynaptic Events
  G Alpha (Z) Signalling Events
  PLC Beta Mediated Events
  Diseases of Glycosylation
  ALK Mutants Bind TKIs
  P2Y Receptors
  CREB1 Phosphorylation Through the Activation of Adenylate Cyclase
  Presynaptic Depolarization and Calcium Channel Opening
  Sphingolipid Catabolism
  Unwinding of DNA
  RNA Polymerase II Transcription
  Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity
  Neurotransmitter Receptors and Postsynaptic Signal Transmission
  2-LTR Circle Formation
  Alpha-Linolenic (Omega3) and Linoleic (Omega6) Acid Metabolism
  Alpha-Linolenic Acid (ALA) Metabolism
  ERBB2 Activates PTK6 Signaling
  Synthesis of PE
  Telomere C-strand Synthesis Initiation
  Transcriptional Regulation of Testis Differentiation
  Ubiquinol Biosynthesis
  Cellular Response to Heat Stress
  G-protein Mediated Events
  Insulin Receptor Signalling Cascade
  PTK6 Regulates RHO GTPases, RAS GTPase and MAP Kinases
  Carnitine Shuttle
  SHC1 Events in ERBB4 Signaling
  Glutamate and Glutamine Metabolism
  IRAK1 Recruits IKK Complex
  IRAK1 Recruits IKK Complex Upon TLR7 8 or 9 Stimulation
  Synthesis of IP2, IP, and Ins in the Cytosol
  TP53 Regulates Transcription of Cell Death Genes With Uncertain Role in P53-Dependent Apoptosis
  Phospholipid Metabolism
  Cell-Cell Communication
  Antiviral Mechanism by IFN-stimulated Genes
  Negative Regulation of TCF-dependent Signaling by WNT Ligand Antagonists
  Phase 2 - Plateau Phase
  ERBB2 Regulates Cell Motility
  Response of EIF2AK1 (HRI) to Heme Deficiency
  Integration of Provirus
  Sphingolipid Metabolism
  SUMOylation of Chromatin Organization Proteins
  Signaling by ERBB4
  Nucleotide-like (Purinergic) Receptors
  PI3K Events in ERBB2 Signaling
  CRMPs in Sema3A Signaling
  FOXO-mediated Transcription of Cell Death Genes
  SUMOylation of DNA Methylation Proteins
  GRB2 Events in ERBB2 Signaling
  Transcription of E2F Targets Under Neg Control by P107 (RBL1) and P130 (RBL2) in Complex With HDAC1
  NRAGE Signals Death Through JNK
  Adherens Junctions Interactions
  Meiotic Synapsis
  PI3K AKT Signaling in Cancer
  PIP3 Activates AKT Signaling
  Interleukin-4 and Interleukin-13 Signaling
  Acyl Chain Remodelling of PI
  Removal of the Flap Intermediate From the C-strand
  FOXO-mediated Transcription of Cell Cycle Genes
  Gene Expression (Transcription)
  O-linked Glycosylation
  HIV Infection
  NCAM Signaling for Neurite Out-Growth
  Pre-NOTCH Processing in Golgi
  Formation of Definitive Endoderm
  Lewis Blood Group Biosynthesis
  Metabolism of Amine-Derived Hormones
  Aflatoxin Activation and Detoxification
  Phase 4 - Resting Membrane Potential
  Processive Synthesis on the C-strand of the Telomere
  RHO GTPases Activate ROCKs
  RHO GTPases Activate CIT
  Glycosphingolipid Biosynthesis
  Glyoxylate Metabolism and Glycine Degradation
  Transcription of E2F Targets Under Negative Control by DREAM Complex
  VEGFR2 Mediated Cell Proliferation
  Fatty Acid Metabolism
  L1CAM Interactions
  Axon Guidance
  Ras Activation Upon Ca2+ Influx Through NMDA Receptor
  FGFR2 Ligand Binding and Activation
  Signaling by PDGFR in Disease
  Synthesis of Leukotrienes (LT) and Eoxins (EX)
  Vitamin B5 (Pantothenate) Metabolism
  Sensory Processing of Sound by Inner Hair Cells of the Cochlea
  Negative Regulation of MET Activity
  CD209 (DC-SIGN) Signaling
  RHO GTPases Activate PAKs
  Regulation of Gene Expression in Beta Cells
  Formation of the Ureteric Bud
  Inactivation of APC C via Direct Inhibition of the APC C Complex
  Inhib of Proteolytic Activity of APC C Required for Onset of Anaphase by Mitotic Spindle Checkpoint
  MHC Class II Antigen Presentation
  NPAS4 Regulates Expression of Target Genes
  Nef-mediates Down Modulation of Cell Surface Receptors by Recruiting Them to Clathrin Adapters
  Acyl Chain Remodelling of PS
  Blood Group Systems Biosynthesis
  Cellular Hexose Transport
  E2F Mediated Regulation of DNA Replication
  ERK MAPK Targets
  Early Phase of HIV Life Cycle
  SHC1 Events in ERBB2 Signaling
  Signaling by ERBB2 TMD JMD Mutants
  Listeria Monocytogenes Entry Into Host Cells
  Reproduction
  trans-Golgi Network Vesicle Budding
  Interleukin-17 Signaling
  Nitric Oxide Stimulates Guanylate Cyclase
  BBSome-mediated Cargo-Targeting to Cilium
  Suppression of Phagosomal Maturation
  Telomere Extension By Telomerase
  Cardiac Conduction
  Class I MHC Mediated Antigen Processing & Presentation
  RHOG GTPase Cycle
  Metabolism of Lipids
  Plasma Lipoprotein Assembly, Remodeling, and Clearance
  Nervous System Development
  Cytosolic Sulfonation of Small Molecules
  Glutamate Neurotransmitter Release Cycle
  Synthesis of Very Long-Chain Fatty acyl-CoAs
  Cell Death Signalling via NRAGE, NRIF and NADE
  ISG15 Antiviral Mechanism
  SUMOylation of DNA Damage Response and Repair Proteins
  Sensory Processing of Sound
  NOTCH3 Activation and Transmission of Signal to the Nucleus
  NOTCH3 Intracellular Domain Regulates Transcription
  Basigin Interactions
  Signaling by ERBB2 KD Mutants
  Metabolism of Cofactors
  APC-Cdc20 Mediated Degradation of Nek2A
  Polymerase Switching on the C-strand of the Telomere
  Fertilization
  Signaling by ERBB2 in Cancer
  WNT Ligand Biogenesis and Trafficking
  PKR-mediated Signaling
  G Alpha (12 13) Signalling Events
  MAPK6 MAPK4 Signaling
  Acyl Chain Remodelling of PC
  Attenuation Phase
  G0 and Early G1
  Degradation of the Extracellular Matrix
  Signaling by Insulin Receptor
  Activation of AMPK Downstream of NMDARs
  Adrenaline,noradrenaline Inhibits Insulin Secretion
  Notch-HLH Transcription Pathway
  CREB1 Phosphorylation Through NMDA Receptor-Mediated Activation of RAS Signaling
  Keratan Sulfate Biosynthesis
  Acyl Chain Remodelling of PE
  Downregulation of ERBB2 Signaling
  EPHA-mediated Growth Cone Collapse
  Energy Dependent Regulation of mTOR by LKB1-AMPK
  Integrin Cell Surface Interactions
  SUMOylation of Intracellular Receptors
  Surfactant Metabolism
  Insulin Receptor Recycling
  Interconversion of Nucleotide Di- and Triphosphates
  Laminin Interactions
  MET Activates PTK2 Signaling
  Signaling by BMP
  Interaction Between L1 and Ankyrins
  Tight Junction Interactions
  MAPK Targets Nuclear Events Mediated by MAP Kinases
  S Phase
  Meiosis
  Opioid Signalling
  Nuclear Signaling by ERBB4
  Packaging Of Telomere Ends
  Phase 0 - Rapid Depolarisation
  DNA Strand Elongation
  Defective TPR May Confer Susceptibility Towards Thyroid Papillary Carcinoma (TPC)
  Regulation of Glucokinase by Glucokinase Regulatory Protein
  Activation of the Pre-Replicative Complex
  Amino Acid Transport Across the Plasma Membrane
  Synthesis of Bile Acids and Bile Salts
  Regulation of TP53 Activity Through Phosphorylation
  Telomere C-strand (Lagging Strand) Synthesis
  Transcriptional Regulation by E2F6
  G Alpha (S) Signalling Events
  HIV Life Cycle
  Nuclear Import of Rev Protein
  SUMOylation of SUMOylation Proteins
  Transcriptional Regulation by NPAS4
  Transport of the SLBP Independent Mature mRNA
  Anti-inflammatory Response Favouring Leishmania Parasite Infection
  Leishmania Parasite Growth and Survival
  RHO GTPase Effectors
  Nuclear Pore Complex (NPC) Disassembly
  Cleavage of the Damaged Purine
  ROS and RNS Production in Phagocytes
  Recognition and Association of DNA Glycosylase With Site Containing an Affected Purine
  Depurination
  Rev-mediated Nuclear Export of HIV RNA
  SMAD2 SMAD3 SMAD4 Heterotrimer Regulates Transcription
  Keratan Sulfate Keratin Metabolism
  Transport of the SLBP Dependant Mature mRNA
  MyD88 Cascade Initiated on Plasma Membrane
  P75 NTR Receptor-Mediated Signalling
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  Activation of ATR in Response to Replication Stress
  Assembly of the ORC Complex at the Origin of Replication
  RHOV GTPase Cycle
  RUNX1 Interacts With Co-Factors Whose Precise Effect on RUNX1 Targets Is Not Known
  Fatty acyl-CoA Biosynthesis
  HSF1-dependent Transactivation
  Sphingolipid De Novo Biosynthesis
  Transport of Ribonucleoproteins Into the Host Nucleus
  SLC Transporter Disorders
  Hedgehog 'Off' State
  VEGFA-VEGFR2 Pathway
  NEP NS2 Interacts With the Cellular Export Machinery
  Apoptotic Cleavage of Cellular Proteins
  Cooperation of PDCL (PhLP1) and TRiC CCT in G-protein Beta Folding
  FLT3 Signaling
  Fanconi Anemia Pathway
  Interactions of Rev With Host Cellular Proteins
  Maturation of Spike Protein 9694548
  Extracellular Matrix Organization
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  Chromatin Modifications During the Maternal to Zygotic Transition (MZT)
  Response of Mtb to Phagocytosis
  Export of Viral Ribonucleoproteins From Nucleus
  SIRT1 Negatively Regulates rRNA Expression
  SUMOylation of Ubiquitinylation Proteins
  MyD88 Dependent Cascade Initiated on Endosome
  SUMO E3 Ligases SUMOylate Target Proteins
  Cleavage of the Damaged Pyrimidine
  RET Signaling
  Recognition and Association of DNA Glycosylase With Site Containing an Affected Pyrimidine
  Depyrimidination
  Diseases Associated With Glycosaminoglycan Metabolism
  MTOR Signalling
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Transport of Inorganic Cations Anions and Amino Acids Oligopeptides
  NS1 Mediated Effects on Host Pathways
  RHOF GTPase Cycle
  Regulation of Beta-Cell Development
  Formation of WDR5-containing Histone-Modifying Complexes
  Transport of Mature mRNA Derived From an Intronless Transcript
  Signaling by VEGF
  Synthesis of DNA
  SUMOylation
  Base-Excision Repair, AP Site Formation
  Signaling by SCF-KIT
  Transport of Mature mRNAs Derived From Intronless Transcripts
  Parasitic Infection Pathways
  Leishmania Infection
  MAPK Family Signaling Cascades
  Toll Like Receptor 9 (TLR9) Cascade
  Bile Acid and Bile Salt Metabolism
  SUMOylation of Transcription Cofactors
  TP53 Regulates Transcription of Cell Death Genes
  PI5P, PP2A and IER3 Regulate PI3K AKT Signaling
  SLC-mediated Transmembrane Transport
  SUMOylation of DNA Replication Proteins
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  Cyclin D Associated Events in G1
  RNA Polymerase II HIV Promoter Escape
  RNA Polymerase II Promoter Escape
  RNA Polymerase II Transcription Initiation
  RNA Polymerase II Transcription Initiation And Promoter Clearance
  RNA Polymerase II Transcription Pre-Initiation And Promoter Opening
  G1 Phase
  HIV Transcription Initiation
  Heme Signaling
  Inhibition of DNA Recombination at Telomere
  Recycling Pathway of L1
  Inositol Phosphate Metabolism
  Cellular Responses to Stimuli
  Negative Regulation of the PI3K AKT Network
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Signaling by NOTCH3
  Viral Messenger RNA Synthesis
  Signaling by ERBB2
  FCGR3A-mediated IL10 Synthesis
  G1 S Transition
  Neurotransmitter Release Cycle
  Cargo Trafficking to the Periciliary Membrane
  Extension of Telomeres
  Transcriptional Activity of SMAD2 SMAD3 SMAD4 Heterotrimer
  Diseases of Metabolism
  Apoptotic Execution Phase
  Nuclear Envelope Breakdown
  Nuclear Receptor Transcription Pathway
  Signaling by EGFR
  snRNP Assembly
  NR1H2 and NR1H3-mediated Signaling
  Ion Homeostasis
  Metabolism of Non-Coding RNA
  RHOJ GTPase Cycle
  Sensory Processing of Sound by Outer Hair Cells of the Cochlea
  Cytokine Signaling in Immune System
  Regulation of PTEN Stability and Activity
  Golgi Associated Vesicle Biogenesis
  HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand
  Interleukin-12 Family Signaling
  Muscle Contraction
  Adaptive Immune System
  Orc1 Removal From Chromatin
  Glycosphingolipid Metabolism
  Interferon Signaling
  tRNA Processing in the Nucleus
  Non-integrin membrane-ECM Interactions
  Arachidonate Metabolism
  RHOQ GTPase Cycle
  Cytoprotection by HMOX1
  Epigenetic Regulation by WDR5-containing Histone Modifying Complexes
  Cdc20 Phospho-APC C Mediated Degradation of Cyclin A
  DNA Damage Telomere Stress Induced Senescence
  Recruitment and ATM-med Phosphorylation of Repair and Signaling Proteins at DNA Double Strand Breaks
  Signaling by Hedgehog
  MITF-M-regulated Melanocyte Development
  Metabolism of Amino Acids and Derivatives
  APC Cdc20 Mediated Degradation of Cell Cycle Proteins Prior to Satisfation of the Checkpoint
  Nuclear Events (Kinase and Transcription Factor Activation)
  DNA Double Strand Break Response
  Regulation of PTEN Gene Transcription
  Transport of Small Molecules
  Cellular Response to Hypoxia
  RHO GTPases Activate PKNs
  Kinesins
  Mitotic G1 Phase and G1 S Transition
  APC C Cdc20 Mediated Degradation of Mitotic Proteins
  Peroxisomal Protein Import
  MAP Kinase Activation
  Translation of Structural Proteins 9694635
  Activation of APC C and APC C Cdc20 Mediated Degradation of Mitotic Proteins
  Bacterial Infection Pathways
  DNA Replication
  O-linked Glycosylation of Mucins
  RAB Geranylgeranylation
  Metabolism
  PTEN Regulation
  Late Phase of HIV Life Cycle
  Regulation of APC C Activators Between G1 S and Early Anaphase
  Toll Like Receptor 4 (TLR4) Cascade
  Signaling by Interleukins
  Circadian Clock
  RHOB GTPase Cycle
  Base Excision Repair
  Transcription of the HIV Genome
  Translocation of SLC2A4 (GLUT4) to the Plasma Membrane
  Pre-NOTCH Transcription and Translation
  Cyclin E Associated Events During G1 S Transition
  Neddylation
  Glycolysis
  Transport of Mature mRNA Derived From an Intron-Containing Transcript
  Death Receptor Signaling
  APC C-mediated Degradation of Cell Cycle Proteins
  Cyclin A Cdk2-associated Events at S Phase Entry
  Regulation of Mitotic Cell Cycle
  Signaling by FGFR2
  Transcriptional Regulation by Small RNAs
  G Alpha (I) Signalling Events
  ECM Proteoglycans
  Regulation of TP53 Activity
  Signaling by TGFB Family Members
  Regulation of Insulin Secretion
  PCP CE Pathway
  Switching of Origins to a Post-Replicative State
  Signaling by GPCR
  Disorders of Transmembrane Transporters
  Late SARS-CoV-2 Infection Events
  GPCR Downstream Signalling
  RNA Polymerase II Pre-transcription Events
  Cellular Senescence
  Negative Epigenetic Regulation of rRNA Expression
  Infection With Mycobacterium Tuberculosis
  Constitutive Signaling by Aberrant PI3K in Cancer
  Transport of Mature Transcript to Cytoplasm
  Transport of Bile Salts and Organic Acids, Metal Ions and Amine Compounds
  Glucose Metabolism
  TP53 Regulates Metabolic Genes
  Toll-like Receptor Cascades
  Nuclear Events Mediated by NFE2L2
  Platelet Homeostasis
  Immune System
  Pre-NOTCH Expression and Processing
  Selective Autophagy
  Chaperonin-mediated Protein Folding
  Signaling by FGFR
  RAF MAP Kinase Cascade
  EPH-Ephrin Signaling
  Telomere Maintenance
  Post-translational Modification Synthesis of GPI-anchored Proteins
  Signaling by ALK Fusions and Activated Point Mutants
  Signaling by ALK in Cancer

## Set B — *without mids* (cell1 small vs cell2 **large**)

`small → large` jumps only.

In [9]:
results_without_mid = run_split_experiments(include_mid=False)

==========================================================================================
GM12878 small vs H1ESC large   (60 genes, 264 reactome terms)
==========================================================================================
  Metabolism of Lipids
  Cytokine Signaling in Immune System
  G Beta Gamma Signalling Through PI3Kgamma
  Membrane Trafficking
  Intra-Golgi and Retrograde Golgi-to-ER Traffic
  Phospholipid Metabolism
  Signaling by CSF1 (M-CSF) in Myeloid Cells
  G-protein Beta Gamma Signalling
  GPVI-mediated Activation Cascade
  FLT3 Signaling
  Rab Regulation of Trafficking
  Vesicle-mediated Transport
  Platelet Activation, Signaling and Aggregation
  Intra-Golgi Traffic
  Signaling by Interleukins
  Synthesis of PIPs at the Plasma Membrane
  Biosynthesis of E-series 18(S)-resolvins
  Toxicity of Botulinum Toxin Type E (botE)
  FLT3 Signaling Through SRC Family Kinases
  GDP-fucose Biosynthesis
  Biosynthesis of EPA-derived SPMs
  Biosynthesis of Lipoxins (LX)
  Toxicity of Botulinum Toxin Type D (botD)
  Toxicity of Botulinum Toxin Type F (botF)
  RUNX3 Regulates Immune Response and Cell Migration
  Immune System
  Biosynthesis of Maresins
  Interleukin-18 Signaling
  Regulation of Gene Expression in Early Pancreatic Precursor Cells
  PI Metabolism
  Nef and Signal Transduction
  Atorvastatin ADME
  Synthesis of 5-Eicosatetraenoic Acids
  Toxicity of Botulinum Toxin Type A (botA)
  RAB GEFs Exchange GTP for GDP on RABs
  Transport of Organic Anions
  Erythropoietin Activates Phosphoinositide-3-kinase (PI3K)
  NOTCH2 Intracellular Domain Regulates Transcription
  Caspase-mediated Cleavage of Cytoskeletal Proteins
  Nephron Development
  The Activation of Arylsulfatases
  Adipogenesis
  Interleukin-4 and Interleukin-13 Signaling
  p130Cas Linkage to MAPK Signaling for Integrins
  GRB2 SOS Provides Linkage to MAPK Signaling for Integrins
  TCR Signaling
  Heme Degradation
  Regulation of Gene Expression in Late Stage (Branching Morphogenesis) Pancreatic Bud Precursor Cells
  FOXO-mediated Transcription of Cell Cycle Genes
  GAB1 Signalosome
  Biosynthesis of DHA-derived SPMs
  Innate Immune System
  Prevention of Phagosomal-Lysosomal Fusion
  Synthesis of Glycosylphosphatidylinositol (GPI)
  Regulation of NF-kappa B Signaling
  Neutrophil Degranulation
  Biosynthesis of Specialized Proresolving Mediators (SPMs)
  Glycerophospholipid Biosynthesis
  Hemostasis
  Synthesis of Leukotrienes (LT) and Eoxins (EX)
  Vitamin B5 (Pantothenate) Metabolism
  Neurotoxicity of Clostridium Toxins
  Regulation of Signaling by CBL
  Interleukin-1 Family Signaling
  MAPK Family Signaling Cascades
  Suppression of Phagosomal Maturation
  Bacterial Infection Pathways
  Other Interleukin Signaling
  Signaling by Erythropoietin
  Inactivation of CSF3 (G-CSF) Signaling
  Insulin Processing
  HDMs Demethylate Histones
  Integrin Signaling
  Effects of PIP2 Hydrolysis
  Peroxisomal Lipid Metabolism
  TRP Channels
  Metabolism of Porphyrins
  Acyl Chain Remodelling of PE
  Phosphorylation of CD3 and TCR Zeta Chains
  TNFs Bind Their Physiological Receptors
  DAP12 Signaling
  The Role of Nef in HIV-1 Replication and Disease Pathogenesis
  Signaling by CSF3 (G-CSF)
  Regulation of TP53 Activity Through Acetylation
  Transcriptional Regulation of Brown and Beige Adipocyte Differentiation
  Transcriptional Regulation of Brown and Beige Adipocyte Differentiation by EBF2
  Glucagon-type Ligand Receptors
  Fatty Acid Metabolism
  Negative Regulators of DDX58 IFIH1 Signaling
  CD28 Co-Stimulation
  Signaling by NOTCH2
  Signaling by High-Kinase Activity BRAF Mutants
  RUNX1 Interacts With Co-Factors Whose Precise Effect on RUNX1 Targets Is Not Known
  Metabolism
  Apoptotic Cleavage of Cellular Proteins
  Response of Mtb to Phagocytosis
  Glycosphingolipid Catabolism
  Platelet Aggregation (Plug Formation)
  Synthesis of PA
  Chromatin Modifications During the Maternal to Zygotic Transition (MZT)
  MAP2K and MAPK Activation
  Generation of Second Messenger Molecules
  Signaling by RAF1 Mutants
  GPCR Downstream Signalling
  Regulation of MITF-M-dependent Genes Involved in Pigmentation
  Regulation of Beta-Cell Development
  Aspirin ADME
  Signaling by SCF-KIT
  Transport of Vitamins, Nucleosides, and Related Molecules
  Uptake and Actions of Bacterial Toxins
  Paradoxical Activation of RAF Signaling by Kinase Inactive BRAF
  Signaling by RAS Mutants
  Signaling by Moderate Kinase Activity BRAF Mutants
  Signaling Downstream of RAS Mutants
  TAK1-dependent IKK and NF-kappa-B Activation
  TBC RABGAPs
  DAP12 Interactions
  ERCC6 (CSB) and EHMT2 (G9a) Positively Regulate rRNA Expression
  Interleukin-10 Signaling
  Kidney Development
  Heme Signaling
  G Alpha (Z) Signalling Events
  Interleukin-3, Interleukin-5 and GM-CSF Signaling
  RNA Polymerase I Transcription Initiation
  Retrograde Transport at the Trans-Golgi-Network
  Signal Transduction
  Apoptotic Execution Phase
  COPI-independent Golgi-to-ER Retrograde Traffic
  Signaling by EGFR
  Regulation of RAS by GAPs
  Transcriptional Activation of Mitochondrial Biogenesis
  Signaling by GPCR
  Chromatin Modifying Enzymes
  Chromatin Organization
  SUMOylation of Chromatin Organization Proteins
  Glycosphingolipid Metabolism
  Arachidonate Metabolism
  HDACs Deacetylate Histones
  Gamma Carboxylation, Hypusinylation, Hydroxylation, and Arylsulfatase Activation
  Regulation of PTEN Gene Transcription
  Peroxisomal Protein Import
  Synthesis of Substrates in N-glycan Biosythesis
  Signaling by BRAF and RAF1 Fusions
  RAB Geranylgeranylation
  Regulation of Endogenous Retroelements by Piwi-interacting RNAs (piRNAs)
  FOXO-mediated Transcription
  RAF MAP Kinase Cascade
  Circadian Clock
  MAPK1 MAPK3 Signaling
  Positive Epigenetic Regulation of rRNA Expression
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  Costimulation by the CD28 Family
  Biosynthesis of the N-glycan Precursor (Dolichol LLO) and Transfer to a Nascent Protein
  RNA Polymerase I Promoter Clearance
  MAPK6 MAPK4 Signaling
  Epigenetic Regulation of Gene Expression
  RNA Polymerase I Transcription
  Oncogenic MAPK Signaling
  Infection With Mycobacterium Tuberculosis
  Transcriptional Regulation of White Adipocyte Differentiation
  Integrin Cell Surface Interactions
  Peptide Hormone Metabolism
  DDX58 IFIH1-mediated Induction of Interferon-Alpha Beta
  Transcriptional Regulation by RUNX3
  TNFR2 Non-Canonical NF-kB Pathway
  Activation of HOX Genes During Differentiation
  Activation of Anterior HOX Genes in Hindbrain Development During Early Embryogenesis
  Post-translational Modification Synthesis of GPI-anchored Proteins
  FCGR Activation
  Oxidative Stress Induced Senescence
  Class B 2 (Secretin Family Receptors)
  MITF-M-dependent Gene Expression
  Mitochondrial Biogenesis
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  Interferon Gamma Signaling
  Interleukin-1 Signaling
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  Epigenetic Regulation of Adipogenesis Genes by MLL3 and MLL4 Complexes
  Epigenetic Regulation of Gene Expression by MLL3 and MLL4 Complexes
  MyD88 Dependent Cascade Initiated on Endosome
  MLL4 and MLL3 Complexes Regulate Expression of PPARG Targets in Adipogenesis and Hepatic Steatosis
  Toll Like Receptor 3 (TLR3) Cascade
  Sphingolipid Metabolism
  Stimuli-sensing Channels
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Maternal to Zygotic Transition (MZT)
  Drug ADME
  MyD88-independent TLR4 Cascade
  FCERI Mediated Ca+2 Mobilization
  TRIF (TICAM1)-mediated TLR4 Signaling
  Toll Like Receptor 9 (TLR9) Cascade
  FCERI Mediated MAPK Activation
  Regulation of Endogenous Retroelements
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  PPARA Activates Gene Expression
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Regulation of Lipid Metabolism by PPARalpha
  Estrogen-dependent Gene Expression
  FCGR3A-mediated IL10 Synthesis
  Host Interactions of HIV Factors
  Metabolism of Water-Soluble Vitamins and Cofactors
  Epigenetic Regulation by WDR5-containing Histone Modifying Complexes
  Golgi-to-ER Retrograde Transport
  MITF-M-regulated Melanocyte Development
  FCGR3A-mediated Phagocytosis
  Parasite Infection
  Leishmania Phagocytosis
  PTEN Regulation
  Toll Like Receptor 4 (TLR4) Cascade
  G Alpha (S) Signalling Events
  Anti-inflammatory Response Favouring Leishmania Parasite Infection
  Leishmania Parasite Growth and Survival
  Regulation of TP53 Activity
  Potential Therapeutics for SARS
  Protein Localization
  Developmental Biology
  Cellular Senescence
  Fcgamma Receptor (FCGR) Dependent Phagocytosis
  Apoptosis
  SUMO E3 Ligases SUMOylate Target Proteins
  Toll-like Receptor Cascades
  SUMOylation
  Ion Channel Transport
  Post-translational Protein Modification
  ESR-mediated Signaling
  Fc Epsilon Receptor (FCERI) Signaling
  Metabolism of Vitamins and Cofactors
  Programmed Cell Death
  Transcriptional Regulation by RUNX1
  Signaling by NOTCH
  Adaptive Immune System
  Signaling by Receptor Tyrosine Kinases
  G Alpha (Q) Signalling Events
  Immunoregulatory Interactions Between a Lymphoid and a non-Lymphoid Cell
  HIV Infection
  Generic Transcription Pathway
  Cell Surface Interactions at the Vascular Wall
  Parasitic Infection Pathways
  Leishmania Infection
  SLC-mediated Transmembrane Transport
  Gene Expression (Transcription)
  Infectious Disease
  Signaling by Nuclear Receptors
  Interferon Signaling
  PIP3 Activates AKT Signaling
  RNA Polymerase II Transcription
  Organelle Biogenesis and Maintenance
  Extracellular Matrix Organization
  Asparagine N-linked Glycosylation
  Intracellular Signaling by Second Messengers
  Transport of Small Molecules
  Transcriptional Regulation by TP53
  Cellular Responses to Stress
  Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers
  Metabolism of Proteins
  Cellular Responses to Stimuli
  GPCR Ligand Binding
  Disease
  SARS-CoV Infections
  Viral Infection Pathways

==========================================================================================
GM12878 small vs HFFC6 large   (79 genes, 352 reactome terms)
==========================================================================================
  Cytokine Signaling in Immune System
  G Beta Gamma Signalling Through PI3Kgamma
  Chaperonin-mediated Protein Folding
  Protein Folding
  Immune System
  G-protein Beta Gamma Signalling
  DNA Strand Elongation
  GPCR Downstream Signalling
  Toll Like Receptor 3 (TLR3) Cascade
  Glucagon-type Ligand Receptors
  MyD88-independent TLR4 Cascade
  TRIF (TICAM1)-mediated TLR4 Signaling
  NOD1 2 Signaling Pathway
  Cooperation of PDCL (PhLP1) and TRiC CCT in G-protein Beta Folding
  L1CAM Interactions
  Signaling by GPCR
  Recycling Pathway of L1
  Extension of Telomeres
  Toll Like Receptor 4 (TLR4) Cascade
  Interferon Signaling
  Antiviral Mechanism by IFN-stimulated Genes
  G Alpha (S) Signalling Events
  IRS Activation
  Nucleotide-binding Domain, Leucine Rich Repeat Containing Receptor (NLR) Signaling Pathways
  NCAM Signaling for Neurite Out-Growth
  MAP Kinase Activation
  RUNX3 Regulates Immune Response and Cell Migration
  Toll-like Receptor Cascades
  CREB Phosphorylation
  Translocation of SLC2A4 (GLUT4) to the Plasma Membrane
  Interleukin-17 Signaling
  Regulation of Gene Expression in Early Pancreatic Precursor Cells
  PKR-mediated Signaling
  PI5P Regulates TP53 Acetylation
  Neurotransmitter Clearance
  Signal Attenuation
  Tetrahydrobiopterin (BH4) Synthesis, Recycling, Salvage and Regulation
  Platelet Homeostasis
  Ribavirin ADME
  Innate Immune System
  Telomere Maintenance
  Reduction of Cytosolic Ca++ Levels
  Unwinding of DNA
  Class B 2 (Secretin Family Receptors)
  Nephron Development
  Purine Salvage
  Cytosolic Iron-Sulfur Cluster Assembly
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  COPI-mediated Anterograde Transport
  Removal of the Flap Intermediate
  Polymerase Switching
  Leading Strand Synthesis
  Uptake and Function of Anthrax Toxins
  Mismatch Repair (MMR) Directed by MSH2 MSH3 (MutSbeta)
  Mismatch Repair (MMR) Directed by MSH2 MSH6 (MutSalpha)
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  MyD88 Dependent Cascade Initiated on Endosome
  Signal Transduction
  Processive Synthesis on the Lagging Strand
  Mismatch Repair
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Synthesis of DNA
  Regulation of Gene Expression in Late Stage (Branching Morphogenesis) Pancreatic Bud Precursor Cells
  Toll Like Receptor 9 (TLR9) Cascade
  Removal of the Flap Intermediate From the C-strand
  Purine Catabolism
  TNF Receptor Superfamily (TNFSF) Members Mediating Non-Canonical NF-kB Pathway
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  G Beta Gamma Signalling Through BTK
  Pre-NOTCH Processing in Golgi
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Chromosome Maintenance
  Transmission Across Chemical Synapses
  Processive Synthesis on the C-strand of the Telomere
  Prostacyclin Signalling Through Prostacyclin Receptor
  TICAM1, RIP1-mediated IKK Complex Recruitment
  Regulation of MITF-M-dependent Genes Involved in Apoptosis
  Microtubule-dependent Trafficking of Connexons From Golgi to the Plasma Membrane
  G Beta Gamma Signalling Through CDC42
  G Beta Gamma Signalling Through PLC Beta
  Lagging Strand Synthesis
  Transport of Connexons to the Plasma Membrane
  Signaling by Interleukins
  MHC Class II Antigen Presentation
  PCNA-Dependent Long Patch Base Excision Repair
  CD209 (DC-SIGN) Signaling
  Presynaptic Function of Kainate Receptors
  ADP Signalling Through P2Y Purinoceptor 12
  Post-chaperonin Tubulin Folding Pathway
  ERK MAPK Targets
  GPCR Ligand Binding
  Activated TAK1 Mediates P38 MAPK Activation
  Nucleotide Salvage
  IKK Complex Recruitment Mediated by RIP1
  Telomere Extension By Telomerase
  Neutrophil Degranulation
  G-protein Activation
  Thromboxane Signalling Through TP Receptor
  ADP Signalling Through P2Y Purinoceptor 1
  Resolution of AP Sites via the Multiple-Nucleotide Patch Replacement Pathway
  Formation of Tubulin Folding Intermediates by CCT TriC
  Gap-filling DNA Repair Synthesis and Ligation in GG-NER
  Metabolism of Cofactors
  DNA Replication
  Gluconeogenesis
  Polymerase Switching on the C-strand of the Telomere
  TNFR1-induced Proapoptotic Signaling
  Hemostasis
  G Alpha (I) Signalling Events
  Activation of AMPK Downstream of NMDARs
  Adrenaline,noradrenaline Inhibits Insulin Secretion
  Platelet Calcium Homeostasis
  TRP Channels
  S Phase
  Myogenesis
  Activation of G Protein Gated Potassium Channels
  G Protein Gated Potassium Channels
  Inhibition of Voltage Gated Ca2+ Channels via Gbeta Gamma Subunits
  DAP12 Signaling
  ER to Golgi Anterograde Transport
  Activation of Kainate Receptors Upon Glutamate Binding
  Insulin Receptor Recycling
  Recognition of DNA Damage by PCNA-containing Replication Complex
  Regulation of TP53 Activity Through Acetylation
  Sealing of the Nuclear Envelope (NE) by ESCRT-III
  Signaling by CSF1 (M-CSF) in Myeloid Cells
  Interaction Between L1 and Ankyrins
  RHO GTPases Activate IQGAPs
  MAPK Targets Nuclear Events Mediated by MAP Kinases
  Cooperation of Prefoldin and TriC CCT in Actin and Tubulin Folding
  Termination of Translesion DNA Synthesis
  Thrombin Signalling Through Proteinase Activated Receptors (PARs)
  Regulation of Necroptotic Cell Death
  Activation of the Pre-Replicative Complex
  Signal Amplification
  Glucagon Signaling in Metabolic Regulation
  TNFR1-induced NF-kappa-B Signaling Pathway
  RIPK1-mediated Regulated Necrosis
  Telomere C-strand (Lagging Strand) Synthesis
  Nuclear Events Stimulated by ALK Signaling in Cancer
  Nucleotide Catabolism
  GPVI-mediated Activation Cascade
  CD28 Co-Stimulation
  Inwardly Rectifying K+ Channels
  Activation of ATR in Response to Replication Stress
  Gap Junction Assembly
  Gene and Protein Expression by JAK-STAT Signaling After Interleukin-12 Stimulation
  Resolution of Abasic Sites (AP Sites)
  FLT3 Signaling
  Chromatin Modifications During the Maternal to Zygotic Transition (MZT)
  Translesion Synthesis by Y Family DNA Polymerases Bypasses Lesions on DNA Template
  Ion Channel Transport
  Generation of Second Messenger Molecules
  Dual Incision in GG-NER
  Transport to the Golgi and Subsequent Modification
  Glucagon-like Peptide-1 (GLP1) Regulates Insulin Secretion
  Regulation of Beta-Cell Development
  ADORA2B Mediated Anti-Inflammatory Cytokines Production
  Activation of GABAB Receptors
  Aggrephagy
  Assembly and Cell Surface Presentation of NMDA Receptors
  GABA B Receptor Activation
  Signaling by SCF-KIT
  Vasopressin Regulates Renal Water Homeostasis via Aquaporins
  Uptake and Actions of Bacterial Toxins
  GPER1 Signaling
  Carboxyterminal Post-Translational Modifications of Tubulin
  DAP12 Interactions
  Interleukin-10 Signaling
  Interleukin-12 Signaling
  Kidney Development
  G Alpha (Z) Signalling Events
  Gap Junction Trafficking
  DNA Damage Bypass
  Neurotransmitter Receptors and Postsynaptic Signal Transmission
  Regulation of TNFR1 Signaling
  Gap Junction Trafficking and Regulation
  Adaptive Immune System
  Neuronal System
  Aquaporin-mediated Transport
  COPI-independent Golgi-to-ER Retrograde Traffic
  Proteasome Assembly
  Synthesis of PIPs at the Plasma Membrane
  Insulin Receptor Signalling Cascade
  Ion Homeostasis
  G Alpha (Q) Signalling Events
  Ion Transport by P-type ATPases
  HSP90 Chaperone Cycle for Steroid Hormone Receptors (SHR) in the Presence of Ligand
  Interleukin-12 Family Signaling
  Immunoregulatory Interactions Between a Lymphoid and a non-Lymphoid Cell
  Cell Cycle
  Chemokine Receptors Bind Chemokines
  Orc1 Removal From Chromatin
  TNF Signaling
  Developmental Biology
  GABA Receptor Activation
  Nuclear Events (Kinase and Transcription Factor Activation)
  Regulated Necrosis
  Gap-filling DNA Repair Synthesis and Ligation in TC-NER
  Kinesins
  Ca2+ Pathway
  Dual Incision in TC-NER
  The Role of GTSE1 in G2 M Progression After G2 Checkpoint
  HDR Through Homologous Recombination (HRR)
  High Laminar Flow Shear Stress Activates Signaling by PIEZO1 and PECAM1 CDH5 KDR in Endothelial Cell
  CD22 Mediated BCR Regulation
  Base Excision Repair
  Platelet Activation, Signaling and Aggregation
  Glycolysis
  Extra-nuclear Estrogen Signaling
  Nuclear Envelope (NE) Reassembly
  ISG15 Antiviral Mechanism
  Transcription-Coupled Nucleotide Excision Repair (TC-NER)
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  Interferon Alpha Beta Signaling
  Costimulation by the CD28 Family
  Regulation of Insulin Secretion
  Switching of Origins to a Post-Replicative State
  G Alpha (12 13) Signalling Events
  Post NMDA Receptor Activation Events
  Signaling by Insulin Receptor
  PI Metabolism
  Global Genome Nucleotide Excision Repair (GG-NER)
  Glucose Metabolism
  Integrin Cell Surface Interactions
  Cell Cycle, Mitotic
  Transcriptional Regulation by RUNX3
  TNFR2 Non-Canonical NF-kB Pathway
  Selective Autophagy
  Pre-NOTCH Expression and Processing
  Opioid Signalling
  Signaling by Receptor Tyrosine Kinases
  Response of Endothelial Cells to Shear Stress
  Activation of NMDA Receptors and Postsynaptic Events
  Signaling by ALK Fusions and Activated Point Mutants
  Signaling by ALK in Cancer
  Cellular Responses to Mechanical Stimuli
  Oxidative Stress Induced Senescence
  Recruitment of NuMA to Mitotic Centrosomes
  MITF-M-dependent Gene Expression
  Axon Guidance
  Antigen Activates B Cell Receptor (BCR) Leading to Generation of Second Messengers
  Asparagine N-linked Glycosylation

/opt/anaconda3/envs/enhancer3D/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

==========================================================================================
H1ESC small vs GM12878 large   (91 genes, 332 reactome terms)
==========================================================================================
  Laminin Interactions
  Tight Junction Interactions
  Extracellular Matrix Organization
  Cell-cell Junction Organization
  Cell Junction Organization
  SUMOylation of DNA Methylation Proteins
  Non-integrin membrane-ECM Interactions
  RHO GTPases Activate ROCKs
  RHO GTPases Activate CIT
  Sema4D Induced Cell Migration and Growth-Cone Collapse
  RHO GTPases Activate PAKs
  SHC1 Events in ERBB2 Signaling
  Sema4D in Semaphorin Signaling
  Cell-Cell Communication
  Syndecan Interactions
  EPHA-mediated Growth Cone Collapse
  EPH-Ephrin Signaling
  Activation of Matrix Metalloproteinases
  RET Signaling
  Gap Junction Trafficking
  Signal Transduction
  Signaling by ERBB2
  Gap Junction Trafficking and Regulation
  Electric Transmission Across Gap Junctions
  Transmission Across Electrical Synapses
  Disinhibition of SNARE Formation
  VLDL Assembly
  Degradation of the Extracellular Matrix
  Signaling by Non-Receptor Tyrosine Kinases
  Signaling by PTK6
  SARS-CoV-2 Targets PDZ Proteins in Cell-Cell Junction
  VLDL Clearance
  Neurexins and Neuroligins
  Signaling by Rho GTPases
  Epithelial-Mesenchymal Transition (EMT) During Gastrulation
  Nectin Necl Trans Heterodimerization
  RHO GTPases Activate PKNs
  Semaphorin Interactions
  Axon Guidance
  Signaling by Rho GTPases, Miro GTPases and RHOBTB3
  Neuronal System
  RHO GTPases Activate Rhotekin and Rhophilins
  ROBO Receptors Bind AKAP5
  EGFR Transactivation by Gastrin
  Nervous System Development
  RHO GTPase Effectors
  Acetylcholine Regulates Insulin Secretion
  Formation of the Posterior Neural Plate
  PI3K Events in ERBB4 Signaling
  HuR (ELAVL1) Binds and Stabilizes mRNA
  Formation of Annular Gap Junctions
  Formation of Apoptosome
  Formation of the Anterior Neural Plate
  Sodium Calcium Exchangers
  TGFBR3 PTM Regulation
  Regulation of the Apoptosome Activity
  Aspartate and Asparagine Metabolism
  Gap Junction Degradation
  Caspase-mediated Cleavage of Cytoskeletal Proteins
  Intracellular Signaling by Second Messengers
  Glutathione Synthesis and Recycling
  Cytochrome C-Mediated Apoptotic Response
  ERBB2 Activates PTK6 Signaling
  Protein-protein Interactions at Synapses
  Repression of WNT Target Genes
  SHC1 Events in ERBB4 Signaling
  PTK6 Regulates RHO GTPases, RAS GTPase and MAP Kinases
  IRAK1 Recruits IKK Complex
  IRAK1 Recruits IKK Complex Upon TLR7 8 or 9 Stimulation
  Defective EXT1 Causes Exostoses 1, TRPS2 and CHDS
  Defective EXT2 Causes Exostoses 2
  Lysosphingolipid and LPA Receptors
  WNT5A-dependent Internalization of FZD4
  Response of EIF2AK1 (HRI) to Heme Deficiency
  p130Cas Linkage to MAPK Signaling for Integrins
  Depolymerization of the Nuclear Lamina
  ERBB2 Regulates Cell Motility
  GRB2 Events in ERBB2 Signaling
  PI3K Events in ERBB2 Signaling
  Regulation of KIT Signaling
  VEGFA-VEGFR2 Pathway
  Visual Phototransduction
  Trafficking of GluR2-containing AMPA Receptors
  Gastrin-CREB Signalling Pathway via PKC and MAPK
  Cargo Recognition for Clathrin-Mediated Endocytosis
  Plasma Lipoprotein Assembly
  VEGFR2 Mediated Cell Proliferation
  Signaling by VEGF
  Apoptotic Factor-Mediated Response
  Defective B3GALT6 Causes EDSP2 and SEMDJL1
  Defective B3GAT3 Causes JDSSDHD
  Defective B4GALT7 Causes EDS, Progeroid Type
  Phase II - Conjugation of Compounds
  Signaling by Receptor Tyrosine Kinases
  Signaling by ERBB2 TMD JMD Mutants
  Gastrulation
  HS-GAG Degradation
  RHO GTPases Activate NADPH Oxidases
  Cytosolic Sulfonation of Small Molecules
  RUNX2 Regulates Osteoblast Differentiation
  Signaling by ERBB2 KD Mutants
  A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis
  Attachment and Entry 9694614
  Signaling by ERBB2 in Cancer
  Platelet Activation, Signaling and Aggregation
  Integrin Signaling
  Activation of AMPK Downstream of NMDARs
  FGFR2 Alternative Splicing
  Response to Elevated Platelet Cytosolic Ca2+
  Myogenesis
  Downregulation of ERBB2 Signaling
  Downstream Signal Transduction
  MET Activates PTK2 Signaling
  Glutamate Binding, Activation of AMPA Receptors and Synaptic Plasticity
  HS-GAG Biosynthesis
  Trafficking of AMPA Receptors
  RUNX2 Regulates Bone Development
  PIP3 Activates AKT Signaling
  Respiratory Syncytial Virus (RSV) Attachment and Entry
  Nuclear Signaling by ERBB4
  Signaling by WNT
  PTEN Regulation
  Clathrin-mediated Endocytosis
  Synthesis of Bile Acids and Bile Salts
  Inactivation, Recovery and Regulation of the Phototransduction Cascade
  DNA Methylation
  Signaling by WNT in Cancer
  The Phototransduction Cascade
  RHO GTPase Cycle
  RHOA GTPase Cycle
  CaM Pathway
  Calmodulin Induced Events
  Molecules Associated With Elastic Fibres
  Gap Junction Assembly
  Glutathione Conjugation
  Ca-dependent Events
  Plasma Lipoprotein Clearance
  Sphingolipid De Novo Biosynthesis
  Cross-presentation of Soluble Exogenous Antigens (Endosomes)
  RHOH GTPase Cycle
  RHOV GTPase Cycle
  RUNX1 Interacts With Co-Factors Whose Precise Effect on RUNX1 Targets Is Not Known
  Apoptotic Cleavage of Cellular Proteins
  Association of TriC CCT With Target Proteins During Biosynthesis
  Platelet Aggregation (Plug Formation)
  PRC2 Methylates Histones and DNA
  DAG and IP3 Signaling
  Defective Pyroptosis
  MET Promotes Cell Motility
  Diseases Associated With Glycosaminoglycan Metabolism
  NCAM1 Interactions
  Deactivation of the Beta-Catenin Transactivating Complex
  Degradation of AXIN
  Apoptosis
  Signaling by SCF-KIT
  SUMO E3 Ligases SUMOylate Target Proteins
  Elastic Fibre Formation
  Retinoid Metabolism and Transport
  NR1H3 & NR1H2 Regulate Gene Expression Linked to Cholesterol Transport and Efflux
  Netrin-1 Signaling
  SUMOylation of Transcription Cofactors
  Bile Acid and Bile Salt Metabolism
  Smooth Muscle Contraction
  Collagen Chain Trimerization
  SUMOylation
  Early SARS-CoV-2 Infection Events
  SUMOylation of RNA Binding Proteins
  NOTCH1 Intracellular Domain Regulates Transcription
  G Alpha (Z) Signalling Events
  Metabolism of Fat-Soluble Vitamins
  PLC Beta Mediated Events
  Signaling by TGFBR3
  Ion Channel Transport
  Chondroitin Sulfate Dermatan Sulfate Metabolism
  EPH-ephrin Mediated Repulsion of Cells
  TCF Dependent Signaling in Response to WNT
  Hemostasis
  Apoptotic Execution Phase
  Nuclear Envelope Breakdown
  NR1H2 and NR1H3-mediated Signaling
  G-protein Mediated Events
  Ion Homeostasis
  Intrinsic Pathway for Apoptosis
  Ion Transport by P-type ATPases
  Regulation of PTEN Stability and Activity
  Heparan Sulfate Heparin (HS-GAG) Metabolism
  Programmed Cell Death
  Transcriptional Regulation by RUNX1
  SUMOylation of Chromatin Organization Proteins
  Signaling by ERBB4
  Signaling by PDGF
  Muscle Contraction
  Neurotransmitter Receptors and Postsynaptic Signal Transmission
  Adherens Junctions Interactions
  Formation of the Beta-Catenin TCF Transactivating Complex
  Assembly of Collagen Fibrils and Other Multimeric Structures
  Regulation of PTEN Gene Transcription
  NCAM Signaling for Neurite Out-Growth
  Ca2+ Pathway
  Collagen Degradation
  RUNX1 Regulates Genes Involved in Megakaryocyte Differentiation and Platelet Function
  G Alpha (Q) Signalling Events
  Collagen Biosynthesis and Modifying Enzymes
  Biological Oxidations
  Immunoregulatory Interactions Between a Lymphoid and a non-Lymphoid Cell
  RHOB GTPase Cycle
  Developmental Biology
  Degradation of Beta-Catenin by the Destruction Complex
  Cell Surface Interactions at the Vascular Wall
  Signaling by NOTCH1
  Signaling by FGFR2
  Plasma Lipoprotein Assembly, Remodeling, and Clearance
  NoRC Negatively Regulates rRNA Expression
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  ECM Proteoglycans
  Regulation of mRNA Stability by Proteins That Bind AU-rich Elements
  SUMOylation of DNA Damage Response and Repair Proteins
  Diseases of Programmed Cell Death
  Regulation of Insulin Secretion
  PCP CE Pathway
  Signaling by MET
  PKR-mediated Signaling
  Post NMDA Receptor Activation Events
  Negative Epigenetic Regulation of rRNA Expression
  Constitutive Signaling by Aberrant PI3K in Cancer
  PI Metabolism
  Integrin Cell Surface Interactions
  RAF MAP Kinase Cascade
  Opioid Signalling
  Collagen Formation
  Adaptive Immune System
  Signaling by FGFR
  Chaperonin-mediated Protein Folding
  Transmission Across Chemical Synapses
  Activation of NMDA Receptors and Postsynaptic Events
  MAPK1 MAPK3 Signaling
  Oxidative Stress Induced Senescence
  Antigen processing-Cross Presentation
  Protein Folding
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  Interleukin-1 Signaling
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  MyD88 Dependent Cascade Initiated on Endosome
  Epigenetic Regulation of Gene Expression
  Transcriptional Regulation by RUNX2
  Sphingolipid Metabolism
  Stimuli-sensing Channels
  Post-translational Protein Phosphorylation
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Transport of Inorganic Cations Anions and Amino Acids Oligopeptides
  Integration of Energy Metabolism
  RSV-host Interactions
  PI3K AKT Signaling in Cancer
  Toll Like Receptor 9 (TLR9) Cascade
  Mitotic Prophase
  PI5P, PP2A and IER3 Regulate PI3K AKT Signaling
  Regulation of Endogenous Retroelements
  Interleukin-4 and Interleukin-13 Signaling
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  Transport of Small Molecules
  SARS-CoV-2 Infection
  MAPK Family Signaling Cascades
  Negative Regulation of the PI3K AKT Network
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs)
  MHC Class II Antigen Presentation
  Glycosaminoglycan Metabolism
  Platelet Degranulation
  Class A 1 (Rhodopsin-like Receptors)
  Cardiac Conduction
  Respiratory Syncytial Virus Infection Pathway
  Beta-catenin Independent WNT Signaling
  Interleukin-1 Family Signaling
  Diseases of Glycosylation
  Toll Like Receptor 4 (TLR4) Cascade
  Class I MHC Mediated Antigen Processing & Presentation
  Metabolism of Steroids
  Antiviral Mechanism by IFN-stimulated Genes
  Signaling by TGFB Family Members
  Cellular Senescence
  Membrane Trafficking
  Toll-like Receptor Cascades
  RAC1 GTPase Cycle
  Ub-specific Processing Proteases
  Peptide Ligand-Binding Receptors
  Metabolism of Vitamins and Cofactors
  Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers
  Signaling by Interleukins
  Signaling by NOTCH
  Signaling by ROBO Receptors
  Phospholipid Metabolism
  Signaling by GPCR
  GPCR Ligand Binding
  SARS-CoV-2-host Interactions
  Immune System
  Generic Transcription Pathway
  Neddylation
  SARS-CoV Infections
  Vesicle-mediated Transport
  Metabolism of Lipids
  SLC-mediated Transmembrane Transport
  Cytokine Signaling in Immune System
  Diseases of Metabolism
  Deubiquitination
  Signaling by Nuclear Receptors
  Interferon Signaling
  Metabolism of Carbohydrates
  RNA Polymerase II Transcription
  Gene Expression (Transcription)
  Antigen Processing Ubiquitination & Proteasome Degradation
  G Alpha (I) Signalling Events
  Metabolism
  GPCR Downstream Signalling
  Sensory Perception
  Post-translational Protein Modification
  Metabolism of Amino Acids and Derivatives
  M Phase
  Cellular Responses to Stress
  Neutrophil Degranulation
  Cell Cycle, Mitotic
  Metabolism of Proteins
  Cellular Responses to Stimuli
  Cell Cycle
  Viral Infection Pathways
  Disease
  Innate Immune System
  Metabolism of RNA
  Infectious Disease

/opt/anaconda3/envs/enhancer3D/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

==========================================================================================
H1ESC small vs HFFC6 large   (95 genes, 282 reactome terms)
==========================================================================================
  Cell-cell Junction Organization
  Cell Junction Organization
  L1CAM Interactions
  Serotonin and Melatonin Biosynthesis
  Sodium-coupled Sulphate, Di- and Tri-Carboxylate Transporters
  IRS Activation
  Defective LFNG Causes SCDO3
  Neurexins and Neuroligins
  Diseases of Glycosylation
  Pre-NOTCH Processing in the Endoplasmic Reticulum
  Signaling by ERBB4
  Epithelial-Mesenchymal Transition (EMT) During Gastrulation
  CREB Phosphorylation
  NCAM Signaling for Neurite Out-Growth
  Cell-Cell Communication
  PIP3 Activates AKT Signaling
  Noncanonical Activation of NOTCH3
  Insulin-like Growth Factor-2 mRNA Binding Proteins (IGF2BPs IMPs VICKZs) Bind RNA
  Defective CHST6 Causes MCDC1
  Diseases Associated With O-glycosylation of Proteins
  Sperm Motility And Taxes
  RHO GTPases Activate Rhotekin and Rhophilins
  Signal Attenuation
  PI3K Events in ERBB4 Signaling
  InlA-mediated Entry of Listeria Monocytogenes Into Host Cells
  Regulation of Endogenous Retroelements by KRAB-ZFP Proteins
  Apoptotic Cleavage of Cell Adhesion Proteins
  Intracellular Signaling by Second Messengers
  Synthesis of PE
  Telomere C-strand Synthesis Initiation
  ERBB2 Activates PTK6 Signaling
  Protein-protein Interactions at Synapses
  SHC1 Events in ERBB4 Signaling
  Glutamate and Glutamine Metabolism
  ERBB2 Regulates Cell Motility
  SUMOylation of DNA Methylation Proteins
  GRB2 Events in ERBB2 Signaling
  PI3K Events in ERBB2 Signaling
  Removal of the Flap Intermediate From the C-strand
  Adaptive Immune System
  Formation of Definitive Endoderm
  Pre-NOTCH Processing in Golgi
  Lewis Blood Group Biosynthesis
  Metabolism of Amine-Derived Hormones
  Sphingolipid Metabolism
  Glycosphingolipid Biosynthesis
  Processive Synthesis on the C-strand of the Telomere
  Signaling by Receptor Tyrosine Kinases
  Generic Transcription Pathway
  PI5P, PP2A and IER3 Regulate PI3K AKT Signaling
  Regulation of Endogenous Retroelements
  Formation of the Ureteric Bud
  CD209 (DC-SIGN) Signaling
  Inactivation of APC C via Direct Inhibition of the APC C Complex
  Inhib of Proteolytic Activity of APC C Required for Onset of Anaphase by Mitotic Spindle Checkpoint
  Signal Transduction
  NPAS4 Regulates Expression of Target Genes
  SHC1 Events in ERBB2 Signaling
  Signaling by ERBB2 TMD JMD Mutants
  Blood Group Systems Biosynthesis
  Listeria Monocytogenes Entry Into Host Cells
  ERK MAPK Targets
  Negative Regulation of the PI3K AKT Network
  Telomere Extension By Telomerase
  NOTCH3 Activation and Transmission of Signal to the Nucleus
  NOTCH3 Intracellular Domain Regulates Transcription
  Signaling by ERBB2 KD Mutants
  MHC Class II Antigen Presentation
  Reproduction
  Diseases of Metabolism
  APC-Cdc20 Mediated Degradation of Nek2A
  Fertilization
  Signaling by ERBB2 in Cancer
  Polymerase Switching on the C-strand of the Telomere
  Notch-HLH Transcription Pathway
  Synthesis of PC
  Keratan Sulfate Biosynthesis
  Downregulation of ERBB2 Signaling
  Insulin Receptor Recycling
  Laminin Interactions
  MET Activates PTK2 Signaling
  Interaction Between L1 and Ankyrins
  RHO GTPases Activate IQGAPs
  Tight Junction Interactions
  MAPK Targets Nuclear Events Mediated by MAP Kinases
  Nuclear Signaling by ERBB4
  Packaging Of Telomere Ends
  PTEN Regulation
  RNA Polymerase II Transcription
  RHO GTPase Effectors
  Synthesis of Bile Acids and Bile Salts
  RHOA GTPase Cycle
  Antigen Processing Ubiquitination & Proteasome Degradation
  Telomere C-strand (Lagging Strand) Synthesis
  Transcriptional Regulation by E2F6
  Transcriptional Regulation by NPAS4
  Cleavage of the Damaged Purine
  Keratan Sulfate Keratin Metabolism
  Recognition and Association of DNA Glycosylase With Site Containing an Affected Purine
  Depurination
  Sphingolipid De Novo Biosynthesis
  RHOV GTPase Cycle
  RUNX1 Interacts With Co-Factors Whose Precise Effect on RUNX1 Targets Is Not Known
  Apoptotic Cleavage of Cellular Proteins
  Cooperation of PDCL (PhLP1) and TRiC CCT in G-protein Beta Folding
  Defective B3GALTL Causes PpS
  MAPK Family Signaling Cascades
  O-glycosylation of TSR Domain-Containing Proteins
  Cellular Senescence
  Cleavage of the Damaged Pyrimidine
  Recognition and Association of DNA Glycosylase With Site Containing an Affected Pyrimidine
  Depyrimidination
  MET Promotes Cell Motility
  Diseases Associated With Glycosaminoglycan Metabolism
  Signaling by Rho GTPases
  Base-Excision Repair, AP Site Formation
  Vasopressin Regulates Renal Water Homeostasis via Aquaporins
  SUMOylation of Transcription Cofactors
  Bile Acid and Bile Salt Metabolism
  Signaling by Rho GTPases, Miro GTPases and RHOBTB3
  Kidney Development
  SUMOylation of RNA Binding Proteins
  Inhibition of DNA Recombination at Telomere
  Recycling Pathway of L1
  Signaling by NOTCH3
  Signaling by ERBB2
  Extension of Telomeres
  Transcriptional and Post-Translational Regulation of MITF-M Expression and Activity
  Metabolism of Amino Acids and Derivatives
  Apoptotic Execution Phase
  Aquaporin-mediated Transport
  Insulin Receptor Signalling Cascade
  Ion Homeostasis
  Signaling by Non-Receptor Tyrosine Kinases
  Signaling by PTK6
  Regulation of PTEN Stability and Activity
  Class I MHC Mediated Antigen Processing & Presentation
  SUMOylation of Chromatin Organization Proteins
  Glycosphingolipid Metabolism
  Adherens Junctions Interactions
  Non-integrin membrane-ECM Interactions
  Meiotic Synapsis
  GABA Receptor Activation
  Cdc20 Phospho-APC C Mediated Degradation of Cyclin A
  DNA Damage Telomere Stress Induced Senescence
  Recruitment and ATM-med Phosphorylation of Repair and Signaling Proteins at DNA Double Strand Breaks
  APC Cdc20 Mediated Degradation of Cell Cycle Proteins Prior to Satisfation of the Checkpoint
  Nuclear Events (Kinase and Transcription Factor Activation)
  DNA Double Strand Break Response
  Regulation of PTEN Gene Transcription
  APC C Cdc20 Mediated Degradation of Mitotic Proteins
  MAP Kinase Activation
  Activation of APC C and APC C Cdc20 Mediated Degradation of Mitotic Proteins
  RAB Geranylgeranylation
  Immunoregulatory Interactions Between a Lymphoid and a non-Lymphoid Cell
  Regulation of APC C Activators Between G1 S and Early Anaphase
  Gene Expression (Transcription)
  Neuronal System
  RHOB GTPase Cycle
  Base Excision Repair
  Neddylation
  Interleukin-17 Signaling
  Pre-NOTCH Transcription and Translation
  APC C-mediated Degradation of Cell Cycle Proteins
  Regulation of Mitotic Cell Cycle
  ECM Proteoglycans
  SUMOylation of DNA Damage Response and Repair Proteins
  Signaling by MET
  MAPK6 MAPK4 Signaling
  Signaling by Insulin Receptor
  Constitutive Signaling by Aberrant PI3K in Cancer
  Transport of Bile Salts and Organic Acids, Metal Ions and Amine Compounds
  RHO GTPase Cycle
  Integrin Cell Surface Interactions
  RAF MAP Kinase Cascade
  Pre-NOTCH Expression and Processing
  Meiosis
  Chaperonin-mediated Protein Folding
  MAPK1 MAPK3 Signaling
  Telomere Maintenance
  Amplification of Signal From Unattached Kinetochores via a MAD2 Inhibitory Signal
  Amplification of Signal From the Kinetochores
  Oxidative Stress Induced Senescence
  Protein Folding
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  COPI-mediated Anterograde Transport
  Metabolism of Carbohydrates
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  Epigenetic Regulation of Gene Expression
  MyD88 Dependent Cascade Initiated on Endosome
  Toll Like Receptor 3 (TLR3) Cascade
  Stimuli-sensing Channels
  Post-translational Protein Phosphorylation
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Extracellular Matrix Organization
  MyD88-independent TLR4 Cascade
  PI3K AKT Signaling in Cancer
  TRIF (TICAM1)-mediated TLR4 Signaling
  Toll Like Receptor 9 (TLR9) Cascade
  Mitotic Spindle Checkpoint
  O-linked Glycosylation
  DNA Repair
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Signaling by NTRK1 (TRKA)
  Toll Like Receptor TLR6 TLR2 Cascade
  EML4 and NUDC in Mitotic Spindle Formation
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Chromosome Maintenance
  Gastrulation
  Metabolism of Lipids
  Axon Guidance
  Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs)
  Resolution of Sister Chromatid Cohesion
  Glycosaminoglycan Metabolism
  Glycerophospholipid Biosynthesis
  Platelet Degranulation
  Cardiac Conduction
  C-type Lectin Receptors (CLRs)
  Response to Elevated Platelet Cytosolic Ca2+
  Post-translational Protein Modification
  Signaling by NTRKs
  Nervous System Development
  MITF-M-regulated Melanocyte Development
  Immune System
  RHO GTPases Activate Formins
  Degradation of the Extracellular Matrix
  Bacterial Infection Pathways
  Toll Like Receptor 4 (TLR4) Cascade
  DNA Double-Strand Break Repair
  CDC42 GTPase Cycle
  Metabolism of Steroids
  ER to Golgi Anterograde Transport
  G Alpha (S) Signalling Events
  Apoptosis
  SUMO E3 Ligases SUMOylate Target Proteins
  Toll-like Receptor Cascades
  SUMOylation
  Separation of Sister Chromatids
  RAC1 GTPase Cycle
  Ion Channel Transport
  Transport to the Golgi and Subsequent Modification
  Programmed Cell Death
  Transcriptional Regulation by RUNX1
  Mitotic Prometaphase
  Muscle Contraction
  Neurotransmitter Receptors and Postsynaptic Signal Transmission
  Signaling by NOTCH
  Phospholipid Metabolism
  Transport of Small Molecules
  Neutrophil Degranulation
  Mitotic Anaphase
  Mitotic Metaphase and Anaphase
  Cell Surface Interactions at the Vascular Wall
  SLC-mediated Transmembrane Transport
  Metabolism of Proteins
  Cell Cycle Checkpoints
  Platelet Activation, Signaling and Aggregation
  Transmission Across Chemical Synapses
  Developmental Biology
  Metabolism
  Asparagine N-linked Glycosylation
  G Alpha (I) Signalling Events
  GPCR Downstream Signalling
  Cell Cycle
  M Phase
  Signaling by GPCR
  Hemostasis
  Cellular Responses to Stress
  Diseases of Signal Transduction by Growth Factor Receptors and Second Messengers
  Signaling by Interleukins
  Innate Immune System
  Cell Cycle, Mitotic
  Cellular Responses to Stimuli
  Membrane Trafficking
  Disease
  Vesicle-mediated Transport
  Metabolism of RNA
  Cytokine Signaling in Immune System
  Infectious Disease

==========================================================================================
HFFC6 small vs GM12878 large   (62 genes, 266 reactome terms)
==========================================================================================
  Extracellular Matrix Organization
  Molecules Associated With Elastic Fibres
  Sphingolipid De Novo Biosynthesis
  Gastrulation
  RND1 GTPase Cycle
  RND3 GTPase Cycle
  RND2 GTPase Cycle
  Elastic Fibre Formation
  Gap Junction Trafficking
  Gap Junction Trafficking and Regulation
  Non-integrin membrane-ECM Interactions
  Electric Transmission Across Gap Junctions
  Formation of Lateral Plate Mesoderm
  Sodium-coupled Phosphate Cotransporters
  Transmission Across Electrical Synapses
  Disinhibition of SNARE Formation
  Ca2+ Pathway
  Formation of Intermediate Mesoderm
  RUNX3 Regulates YAP1-mediated Transcription
  Axon Guidance
  Developmental Biology
  ROBO Receptors Bind AKAP5
  Regulation of PTEN Localization
  Downregulation of ERBB4 Signaling
  EGFR Transactivation by Gastrin
  Acetylcholine Regulates Insulin Secretion
  Formation of the Posterior Neural Plate
  HuR (ELAVL1) Binds and Stabilizes mRNA
  Nervous System Development
  EPH-Ephrin Signaling
  Formation of Annular Gap Junctions
  Formation of the Anterior Neural Plate
  Pexophagy
  Regulation of CDH11 Function
  Gap Junction Degradation
  Specification of Primordial Germ Cells
  Cargo Recognition for Clathrin-Mediated Endocytosis
  Formation of Axial Mesoderm
  Glycogen Breakdown (Glycogenolysis)
  Uptake and Function of Anthrax Toxins
  Sphingolipid Metabolism
  WNT5A-dependent Internalization of FZD4
  YAP1- and WWTR1 (TAZ)-stimulated Gene Expression
  Depolymerization of the Nuclear Lamina
  cGMP Effects
  Rap1 Signalling
  Regulation of KIT Signaling
  Germ Layer Formation at Gastrulation
  Specification of the Neural Plate Border
  Trafficking of GluR2-containing AMPA Receptors
  Formation of the Nephric Duct
  Gastrin-CREB Signalling Pathway via PKC and MAPK
  Assembly of Active LPL and LIPC Lipase Complexes
  RHO GTPases Activate ROCKs
  RHO GTPases Activate CIT
  VEGFR2 Mediated Cell Proliferation
  Sema4D Induced Cell Migration and Growth-Cone Collapse
  Formation of the Ureteric Bud
  RHO GTPases Activate PAKs
  Beta-catenin Independent WNT Signaling
  SHC1 Events in ERBB2 Signaling
  Activated TAK1 Mediates P38 MAPK Activation
  Nitric Oxide Stimulates Guanylate Cyclase
  RNA Polymerase III Transcription Termination
  Sema4D in Semaphorin Signaling
  Other Interleukin Signaling
  RHO GTPases Activate NADPH Oxidases
  RUNX2 Regulates Osteoblast Differentiation
  Clathrin-mediated Endocytosis
  Glycogen Metabolism
  Syndecan Interactions
  EPHA-mediated Growth Cone Collapse
  Surfactant Metabolism
  Laminin Interactions
  Regulation of CDH11 Expression and Function
  Glutamate Binding, Activation of AMPA Receptors and Synaptic Plasticity
  Interaction Between L1 and Ankyrins
  Trafficking of AMPA Receptors
  RUNX2 Regulates Bone Development
  Phase 0 - Rapid Depolarisation
  Inactivation, Recovery and Regulation of the Phototransduction Cascade
  Regulation of Expression and Function of Type II Classical Cadherins
  Regulation of Homotypic Cell-Cell Adhesion
  Plasma Lipoprotein Remodeling
  The Phototransduction Cascade
  CaM Pathway
  Calmodulin Induced Events
  Gap Junction Assembly
  Ca-dependent Events
  Cross-presentation of Soluble Exogenous Antigens (Endosomes)
  RHOV GTPase Cycle
  Defective B3GALTL Causes PpS
  Maturation of Spike Protein 9694548
  O-glycosylation of TSR Domain-Containing Proteins
  Association of TriC CCT With Target Proteins During Biosynthesis
  RHOU GTPase Cycle
  Sensory Perception of Sweet, Bitter, and Umami (Glutamate) Taste
  RET Signaling
  DAG and IP3 Signaling
  RNA Polymerase III Abortive And Retractive Initiation
  RNA Polymerase III Transcription
  RHOF GTPase Cycle
  Signaling by SCF-KIT
  Netrin-1 Signaling
  Smooth Muscle Contraction
  Uptake and Actions of Bacterial Toxins
  Muscle Contraction
  Kidney Development
  Sensory Perception of Taste
  G Alpha (Z) Signalling Events
  PLC Beta Mediated Events
  Signaling by ERBB2
  EPH-ephrin Mediated Repulsion of Cells
  G Alpha (Q) Signalling Events
  Nuclear Envelope Breakdown
  RHOD GTPase Cycle
  G-protein Mediated Events
  Signaling by Rho GTPases
  RHOJ GTPase Cycle
  Regulation of PTEN Stability and Activity
  Signaling by Rho GTPases, Miro GTPases and RHOBTB3
  Signaling by ERBB4
  Adherens Junctions Interactions
  Formation of Paraxial Mesoderm
  RHOQ GTPase Cycle
  Recruitment and ATM-med Phosphorylation of Repair and Signaling Proteins at DNA Double Strand Breaks
  DNA Double Strand Break Response
  RHO GTPases Activate PKNs
  MAP Kinase Activation
  Translation of Structural Proteins 9694635
  Semaphorin Interactions
  RUNX1 Regulates Genes Involved in Megakaryocyte Differentiation and Platelet Function
  RHOB GTPase Cycle
  Diseases Associated With O-glycosylation of Proteins
  Interleukin-17 Signaling
  Hedgehog 'On' State
  RHOC GTPase Cycle
  RHOG GTPase Cycle
  Plasma Lipoprotein Assembly, Remodeling, and Clearance
  ISG15 Antiviral Mechanism
  Regulation of mRNA Stability by Proteins That Bind AU-rich Elements
  Regulation of Insulin Secretion
  PCP CE Pathway
  Late SARS-CoV-2 Infection Events
  Signaling by WNT
  RHO GTPase Effectors
  Transcriptional Regulation of White Adipocyte Differentiation
  Transcriptional Regulation by RUNX3
  Platelet Homeostasis
  Selective Autophagy
  Opioid Signalling
  Chaperonin-mediated Protein Folding
  Cell-cell Junction Organization
  Oxidative Stress Induced Senescence
  RAC3 GTPase Cycle
  Antigen processing-Cross Presentation
  Protein Folding
  Intracellular Signaling by Second Messengers
  MyD88 Cascade Initiated on Plasma Membrane
  Toll Like Receptor 10 (TLR10) Cascade
  Toll Like Receptor 5 (TLR5) Cascade
  SLC Transporter Disorders
  Hedgehog 'Off' State
  VEGFA-VEGFR2 Pathway
  Visual Phototransduction
  TRAF6 Mediated Induction of NFkB and MAP Kinases Upon TLR7 8 or 9 Activation
  Epigenetic Regulation of Adipogenesis Genes by MLL3 and MLL4 Complexes
  Epigenetic Regulation of Gene Expression by MLL3 and MLL4 Complexes
  MyD88 Dependent Cascade Initiated on Endosome
  MLL4 and MLL3 Complexes Regulate Expression of PPARG Targets in Adipogenesis and Hepatic Steatosis
  Toll Like Receptor 3 (TLR3) Cascade
  Transcriptional Regulation by RUNX2
  Post-translational Protein Phosphorylation
  Toll Like Receptor 7 8 (TLR7 8) Cascade
  Transport of Inorganic Cations Anions and Amino Acids Oligopeptides
  Signaling by VEGF
  Integration of Energy Metabolism
  MyD88-independent TLR4 Cascade
  Adipogenesis
  TRIF (TICAM1)-mediated TLR4 Signaling
  Toll Like Receptor 9 (TLR9) Cascade
  Mitotic Prophase
  O-linked Glycosylation
  MyD88 MAL(TIRAP) Cascade Initiated on Plasma Membrane
  Toll Like Receptor TLR6 TLR2 Cascade
  PPARA Activates Gene Expression
  Toll Like Receptor 2 (TLR2) Cascade
  Toll Like Receptor TLR1 TLR2 Cascade
  Cell Junction Organization
  Regulation of Lipid Metabolism by PPARalpha
  L1CAM Interactions
  Membrane Trafficking
  Regulation of IGF Transport and Uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs)
  Class I MHC Mediated Antigen Processing & Presentation
  Reproduction
  Cardiac Conduction
  Response to Elevated Platelet Cytosolic Ca2+
  Epigenetic Regulation by WDR5-containing Histone Modifying Complexes
  Signaling by Hedgehog
  Bacterial Infection Pathways
  Macroautophagy
  PTEN Regulation
  Neuronal System
  Diseases of Glycosylation
  Toll Like Receptor 4 (TLR4) Cascade
  RHOA GTPase Cycle
  Hemostasis
  DNA Double-Strand Break Repair
  CDC42 GTPase Cycle
  Gene Expression (Transcription)
  Cell-Cell Communication
  Factors Involved in Megakaryocyte Development and Platelet Production
  Antiviral Mechanism by IFN-stimulated Genes
  Autophagy
  Disorders of Transmembrane Transporters
  Cellular Senescence
  RHO GTPase Cycle
  Signaling by Interleukins
  Vesicle-mediated Transport
  Toll-like Receptor Cascades
  Metabolism of Lipids
  Cytokine Signaling in Immune System
  RAC1 GTPase Cycle
  Neutrophil Degranulation
  Peptide Ligand-Binding Receptors
  Transcriptional Regulation by RUNX1
  Neurotransmitter Receptors and Postsynaptic Signal Transmission
  Signaling by ROBO Receptors
  Adaptive Immune System
  Signaling by Receptor Tyrosine Kinases
  Immune System
  Generic Transcription Pathway
  SLC-mediated Transmembrane Transport
  Platelet Activation, Signaling and Aggregation
  Diseases of Metabolism
  Transmission Across Chemical Synapses
  Signal Transduction
  Interferon Signaling
  PIP3 Activates AKT Signaling
  GPCR Downstream Signalling
  Sensory Perception
  Metabolism of Carbohydrates
  Epigenetic Regulation of Gene Expression
  Antigen Processing Ubiquitination & Proteasome Degradation
  RNA Polymerase II Transcription
  DNA Repair
  SARS-CoV-2 Infection
  G Alpha (I) Signalling Events
  Class A 1 (Rhodopsin-like Receptors)
  Signaling by GPCR
  Transport of Small Molecules
  M Phase
  Innate Immune System
  GPCR Ligand Binding
  SARS-CoV Infections
  Cell Cycle, Mitotic
  Metabolism
  Cell Cycle
  Metabolism of Proteins
  Disease
  Metabolism of RNA
  Cellular Responses to Stress
  Infectious Disease
  Cellular Responses to Stimuli
  Post-translational Protein Modification
  Viral Infection Pathways


## Export terms to `export/`

* `split_celllines_reactome_terms.txt` — human-readable term lists for **all**
  terms, both sets, all 12 experiments, with the **FDR** (Enrichr Adjusted
  P-value) shown next to each term.
* `split_celllines_reactome_terms_fdr_significant.txt` — same layout but keeping
  **only terms with FDR < 0.05**.
* `split_celllines_reactomes.csv` — tidy long-format table (Experiment, Jump set,
  Gene count + the full Enrichr columns, incl. Adjusted P-value/FDR) for
  downstream use.

In [10]:
# FDR in Enrichr output == the "Adjusted P-value" column (Benjamini-Hochberg).
FDR_COL = "Adjusted P-value"
FDR_THRESHOLD = 0.05


def _write_terms(fh, exp_label, gene_names, reactomes, fdr_threshold=None):
    df = reactomes
    if fdr_threshold is not None:
        df = df[df[FDR_COL] < fdr_threshold]
    fh.write("=" * 90 + "\n")
    fh.write(f"{exp_label}   ({len(gene_names)} genes, {len(df)} reactome terms)\n")
    fh.write("=" * 90 + "\n")
    for _, row in df.iterrows():
        fh.write(f"  {row['Term']}\t(FDR={row[FDR_COL]:.3g})\n")
    fh.write("\n")


def export_results(all_sets, txt_path, csv_path, txt_sig_path):
    # all_sets: list of (set_label, results_dict{exp_label: (gene_names, reactomes_df)})
    # txt_path     -> all terms, with FDR shown next to each term
    # txt_sig_path -> only terms with FDR < FDR_THRESHOLD, with FDR shown
    for path, threshold in ((txt_path, None), (txt_sig_path, FDR_THRESHOLD)):
        with open(path, "w") as fh:
            if threshold is not None:
                fh.write(f"# Only Reactome terms with FDR < {threshold}\n\n")
            for set_label, results in all_sets:
                fh.write("#" * 90 + "\n")
                fh.write(f"# {set_label}\n")
                fh.write("#" * 90 + "\n\n")
                for exp_label, (gene_names, reactomes) in results.items():
                    _write_terms(fh, exp_label, gene_names, reactomes, fdr_threshold=threshold)

    frames = []
    for set_label, results in all_sets:
        for exp_label, (gene_names, reactomes) in results.items():
            frame = reactomes.copy()
            frame.insert(0, "Experiment", exp_label)
            frame.insert(1, "Jump set", set_label)
            frame.insert(2, "Gene count", len(gene_names))
            frames.append(frame)
    combined = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    combined.to_csv(csv_path, index=False)
    return combined


split_reactomes_combined = export_results(
    [
        ("with mids (small -> mid/large)", results_with_mid),
        ("without mids (small -> large)", results_without_mid),
    ],
    "export/split_celllines_reactome_terms.txt",
    "export/split_celllines_reactomes.csv",
    "export/split_celllines_reactome_terms_fdr_significant.txt",
)
print("wrote export/split_celllines_reactome_terms.txt")
print("wrote export/split_celllines_reactome_terms_fdr_significant.txt")
print("wrote export/split_celllines_reactomes.csv")
split_reactomes_combined.head()

wrote export/split_celllines_reactome_terms.txt
wrote export/split_celllines_reactome_terms_fdr_significant.txt
wrote export/split_celllines_reactomes.csv

,Experiment,Jump set,Gene count,Term,P-value,Adjusted P-value,Overlap,Combined Score,Genes,Genes Ratio,Genes Number
0,GM12878 small vs H1ESC mid/large,with mids (small -> mid/large),242,Cytokine Signaling in Immune System,3.342591e-11,2.012240e-08,33/776,107.900618,CD40;CIITA;PTAFR;NLRC5;PIK3CD;USP18;ALOX5;GRAP...,0.136364,33
1,GM12878 small vs H1ESC mid/large,with mids (small -> mid/large),242,Immune System,8.416147e-11,2.533260e-08,58/2150,69.359818,CD40;CIITA;ARPC1B;ICAM3;CGAS;PIK3CD;ITGAL;ADGR...,0.239669,58
2,GM12878 small vs H1ESC mid/large,with mids (small -> mid/large),242,Signaling by Interleukins,7.313282e-09,1.467532e-06,22/452,92.721605,IL15RA;MEF2C;SYK;PTAFR;NLRC5;PIK3CD;IL16;USP18...,0.090909,22
3,GM12878 small vs H1ESC mid/large,with mids (small -> mid/large),242,"Interleukin-3, Interleukin-5 and GM-CSF Signaling",9.446440e-07,1.421689e-04,7/48,217.425398,HCK;TEC;SYK;BLNK;PIK3CD;PTPN6;JAK3,0.028926,7
4,GM12878 small vs H1ESC mid/large,with mids (small -> mid/large),242,GPVI-mediated Activation Cascade,2.168132e-06,2.610431e-04,6/35,246.704439,SYK;PLCG2;RHOG;PTPN6;PIK3R6;PIK3R5,0.024793,6